Repository centreon/centreon-plugins, pull requests merged in 2021-12, with the labels that each got.

#3274 plugin(add) apps-dynamics-ax
  apps/dynamics/ax/mode/ediorder.pm
Labels: mode, new

#3295 (plugin) fix containerstatus - add ready container state management
  cloud/prometheus/direct/kubernetes/mode/containerstatus.pm
Labels: fix

#3344 (plugin): cloud::aws::fsx - add AWS/FSx shared filesystems monitoring
  cloud/aws/fsx/mode/datausage.pm
  cloud/aws/fsx/mode/discovery.pm
  cloud/aws/fsx/mode/freespace.pm
  cloud/aws/fsx/plugin.pm
Labels: new

#3351 (plugin) check kubernetes cluster through azure API
  cloud/azure/compute/aks/mode/allocatableresources.pm
  cloud/azure/compute/aks/mode/cpu.pm
  cloud/azure/compute/aks/mode/discovery.pm
  cloud/azure/compute/aks/mode/storage.pm
  cloud/azure/compute/aks/mode/traffic.pm
  cloud/azure/compute/aks/mode/unneedednodes.pm
  cloud/azure/compute/aks/plugin.pm
Labels: new

#3354 (plugin) network::fortinet::fortigate::snmp - mode sd-wan carriage return
  centreon/common/fortinet/fortigate/snmp/mode/sdwan.pm
Labels: fix

#3355 (plugin) cloud::azure::compute::aks - change mode names
  cloud/azure/compute/aks/plugin.pm
Labels: enhancement

#3358 (plugin) hardware::pdu::apc::snmp - mode load better management of some oids missing
  hardware/pdu/apc/snmp/mode/load.pm
Labels: enhancement

#3359 (plugin) hardware::server::dell::omem::snmp::plugin
  hardware/server/dell/omem/snmp/mode/components/chassis.pm
  hardware/server/dell/omem/snmp/mode/components/health.pm
  hardware/server/dell/omem/snmp/mode/components/psu.pm
  hardware/server/dell/omem/snmp/mode/components/temperature.pm
  hardware/server/dell/omem/snmp/mode/hardware.pm
  hardware/server/dell/omem/snmp/plugin.pm
Labels: new

#3360 (plugin) add azure/aks health mode
  cloud/azure/compute/aks/mode/health.pm
  cloud/azure/compute/aks/plugin.pm
Labels: new
