Repository centreon/centreon-plugins, pull requests merged in 2021-06, with the labels that each got.

#2842 fix(custom): Azure API fix Loganalytics request
  cloud/azure/custom/api.pm
Labels: bug, plugin

#2851 Add support for checking memory slots on HPE Proliant servers
  hardware/server/hp/proliant/snmp/mode/components/memory.pm
  hardware/server/hp/proliant/snmp/mode/hardware.pm
Labels: enhancement, mode

#2855 enh(plugin)cAdvisor plugin enhancements
  cloud/cadvisor/restapi/custom/api.pm
  cloud/cadvisor/restapi/mode/containerusage.pm
  cloud/cadvisor/restapi/mode/diskio.pm
  cloud/cadvisor/restapi/mode/nodestatus.pm
  cloud/cadvisor/restapi/mode/traffic.pm
Labels: enhancement

#2808 new(plugin): Azure Redis Cache with 10 modes + discovery
  cloud/azure/database/redis/mode/cachelatency.pm
  cloud/azure/database/redis/mode/cachethroughput.pm
  cloud/azure/database/redis/mode/cacheusage.pm
  cloud/azure/database/redis/mode/clients.pm
  cloud/azure/database/redis/mode/cpu.pm
  cloud/azure/database/redis/mode/discovery.pm
  cloud/azure/database/redis/mode/errors.pm
  cloud/azure/database/redis/mode/health.pm
  cloud/azure/database/redis/mode/load.pm
  cloud/azure/database/redis/mode/memory.pm
  cloud/azure/database/redis/mode/operations.pm
  cloud/azure/database/redis/plugin.pm
Labels: new, plugin

#2854 Adds 'other' and 'total' metrics for netapp plugin
  storage/netapp/ontap/restapi/mode/cluster.pm
  storage/netapp/ontap/restapi/mode/volumes.pm
Labels: enhancement

#2805 new(plugin): Azure CDN with 4 modes + discovery
  cloud/azure/network/cdn/mode/discovery.pm
  cloud/azure/network/cdn/mode/hitratio.pm
  cloud/azure/network/cdn/mode/latency.pm
  cloud/azure/network/cdn/mode/requests.pm
  cloud/azure/network/cdn/mode/response.pm
  cloud/azure/network/cdn/plugin.pm
Labels: new, plugin

#2815 new(plugin): Azure StorageSync service (discovery, 2 modes, 3 metrics)
  cloud/azure/storage/storagesync/mode/discovery.pm
  cloud/azure/storage/storagesync/mode/filessync.pm
  cloud/azure/storage/storagesync/mode/recallls.pm
  cloud/azure/storage/storagesync/mode/serverstatus.pm
  cloud/azure/storage/storagesync/plugin.pm
Labels: new, plugin

#2893 fix(plugin)bladechassis-oid-mixed-up
  hardware/server/hp/bladechassis/snmp/mode/components/blade.pm
Labels: bug

#2892 enh(qnap) Add processcount standard mode
  storage/qnap/snmp/plugin.pm
Labels: enhancement

#2894 fix(plugin)bypass-perl-error-messy-commvault-api
  apps/backup/commvault/commserve/restapi/custom/api.pm
Labels: bug
