Repository centreon/centreon-plugins, pull requests merged in 2021-11, with the labels that each got.

#3224 enh(disco) nmap discovery
  apps/nmap/cli/mode/discovery.pm
Labels: enhancement

#3227 Add size in liststorages disco format
  os/linux/local/mode/liststorages.pm
Labels: enhancement

#3267 enh(plugin): VTOM REST API metricsv2
  apps/vtom/restapi/mode/jobstatus.pm
  apps/vtom/restapi/plugin.pm
Labels: enhancement, plugin

#3272 enh(plugin): Asterisk AMI & SNMP MetricsV2
  apps/voip/asterisk/ami/mode/channelusage.pm
  apps/voip/asterisk/ami/mode/dahdistatus.pm
  apps/voip/asterisk/ami/mode/sippeersusage.pm
  apps/voip/asterisk/ami/plugin.pm
  apps/voip/asterisk/snmp/mode/channelusage.pm
  apps/voip/asterisk/snmp/plugin.pm
Labels: enhancement, plugin

#3271 enh(plugin): Netbackup MetricsV2
  apps/backup/netbackup/local/mode/dedupstatus.pm
  apps/backup/netbackup/local/mode/drivecleaning.pm
  apps/backup/netbackup/local/mode/jobstatus.pm
  apps/backup/netbackup/local/mode/tapeusage.pm
  apps/backup/netbackup/local/plugin.pm
Labels: enhancement, plugin

#3280 (plugin) patch edge case on empty JSON with Veeam tape-jobs mode
  apps/backup/veeam/local/mode/tapejobs.pm
Labels: fix

#3265 (plugin)refactoring-azure-virtual-networks
  cloud/azure/custom/api.pm
  cloud/azure/custom/azcli.pm
  cloud/azure/network/virtualnetwork/mode/listvirtualnetworks.pm
  cloud/azure/network/virtualnetwork/mode/peeringsstatus.pm
Labels: enhancement, breaking_change
