Repository centreon/centreon-plugins, pull requests merged in 2022-06, with the labels that each got.

#3702 (plugin) apps::protocols::cifs - add mode files
  apps/protocols/cifs/mode/files.pm
  apps/protocols/cifs/plugin.pm
Labels: enhancement

#3703 (plugin) apps::protocols::nrpe - enhance perfdata management in NRPE …
  apps/protocols/nrpe/custom/nrpe.pm
  apps/protocols/nrpe/mode/query.pm
Labels: enhancement

#3705 (plugin) os::hpux::local - use backend ssh + new mode list-storages
  os/hpux/local/mode/inodes.pm
  os/hpux/local/mode/liststorages.pm
  os/hpux/local/mode/storage.pm
  os/hpux/local/plugin.pm
Labels: enhancement

#3711 (core) add snmp tls options
  centreon/plugins/snmp.pm
Labels: enhancement

#3713 (plugin) network::fortinet::fortigate::snmp - mode sdwan add packetLo…
  centreon/common/fortinet/fortigate/snmp/mode/sdwan.pm
Labels: enhancement

#3718 (plugin) apps::monitoring::speedtest - new
  apps/monitoring/speedtest/mode/internetbandwidth.pm
  apps/monitoring/speedtest/plugin.pm
  apps/protocols/whois/mode/domain.pm
Labels: new

#3719 (plugin) os::windows::local - harden regexp source (again)
  os/windows/local/mode/ntp.pm
Labels: bugfix

#3722 (plugin) apps::pvx::restapi - harden default filter regexp
  apps/pvx/restapi/custom/api.pm
Labels: bugfix

#3730 enh(ci): Debian pkg centreon plugins delivery
  Jenkinsfile
Labels: area/ci

#3731 hotfix(ci): bad jenkinsfile
  Jenkinsfile
Labels: area/ci

#3732 (plugin) network::cisco::standard::snmp - fix Math::BigInt error
  centreon/common/cisco/standard/snmp/mode/qosusage.pm
Labels: bugfix

#3736 (plugin) network::cisco::standard::snmp - fix Math::BigInt error bdstr
  centreon/common/cisco/standard/snmp/mode/qosusage.pm
Labels: bugfix

#3740 (plugin) network::nortel::standard::snmp - add stack mode
  network/nortel/standard/snmp/mode/stack.pm
  network/nortel/standard/snmp/plugin.pm
Labels: enhancement

#3739 (plugin) cloud::aws::sns/sqs - migrate AWS SNS & SQS Service Disco to Host Disco
  cloud/aws/sns/mode/discovery.pm
  cloud/aws/sns/plugin.pm
  cloud/aws/sqs/mode/discovery.pm
  cloud/aws/sqs/plugin.pm
Labels: enhancement

#3743 prepare release 20220616
  changelog
Labels: enhancement

#3744 (plugin) storage::hp::p2000::xmlapi - add mode time
  storage/hp/p2000/xmlapi/mode/time.pm
  storage/hp/p2000/xmlapi/plugin.pm
Labels: enhancement

#3747 (http) fix catch timeout message backend lwp
  centreon/plugins/backend/http/lwp.pm
Labels: bugfix

#3749 (plugin) apps::protocols::http - mode collection catch boolean value …
  apps/protocols/http/mode/collection.pm
Labels: bugfix

#3748 (plugin) os::linux::local - mode cmd-return enhance expression capabi…
  os/linux/local/mode/cmdreturn.pm
Labels: enhancement

#3737 (plugin) apps::dynatrace::restapi - enhance Dynatrace plugin with new modes and new metrics
  apps/monitoring/dynatrace/restapi/custom/api.pm
  apps/monitoring/dynatrace/restapi/mode/apdex.pm
  apps/monitoring/dynatrace/restapi/mode/availability.pm
  apps/monitoring/dynatrace/restapi/mode/events.pm
  apps/monitoring/dynatrace/restapi/mode/problems.pm
  apps/monitoring/dynatrace/restapi/plugin.pm
Labels: enhancement

#3750 (plugin) aws::billing::plugin - adding discovery mode
  cloud/aws/billing/mode/discovery.pm
  cloud/aws/billing/plugin.pm
Labels: enhancement

#3753 (plugin) apps::monitoring::kadiska - update credential storage
  apps/monitoring/kadiska/custom/api.pm
  apps/monitoring/kadiska/mode/watcherstatistics.pm
Labels: enhancement
