Repository centreon/centreon-plugins, pull requests merged in 2022-05, with the labels that each got.

#3627 (plugin) notification::microsoft::office365::teams - fix help
  notification/microsoft/office365/teams/mode/alert.pm
Labels: fix

#3629 (core) add password manager environment
  centreon/plugins/passwordmgr/environment.pm
Labels: enhancement

#3630 (core) add option to change default http backend
  centreon/plugins/http.pm
Labels: enhancement

#3622 (plugin) apps::monitoring::kadiska - add new plugin for Kadiska
  apps/monitoring/kadiska/custom/api.pm
  apps/monitoring/kadiska/mode/liststations.pm
  apps/monitoring/kadiska/mode/listtargets.pm
  apps/monitoring/kadiska/mode/listwatchers.pm
  apps/monitoring/kadiska/mode/tracerstatistics.pm
  apps/monitoring/kadiska/mode/watcherstatistics.pm
  apps/monitoring/kadiska/plugin.pm
Labels: new

#3635 (plugin) hardware::server::hp::proliant::snmp mode hardware - force new perfdata
  hardware/server/hp/proliant/snmp/mode/components/fan.pm
  hardware/server/hp/proliant/snmp/mode/components/psu.pm
  hardware/server/hp/proliant/snmp/mode/components/temperature.pm
  hardware/server/hp/proliant/snmp/mode/hardware.pm
Labels: enhancement

#3637 (plugin) hardware::sensors::jacarta::snmp - support interseptor
  hardware/sensors/jacarta/snmp/mode/components/humidity.pm
  hardware/sensors/jacarta/snmp/mode/components/input.pm
  hardware/sensors/jacarta/snmp/mode/components/resources.pm
  hardware/sensors/jacarta/snmp/mode/components/temperature.pm
  hardware/sensors/jacarta/snmp/mode/sensors.pm
  hardware/sensors/jacarta/snmp/plugin.pm
Labels: enhancement

#3638 (plugin) apps::monitoring:kadiska - removing old perfdata labels
  apps/monitoring/kadiska/mode/tracerstatistics.pm
  apps/monitoring/kadiska/mode/watcherstatistics.pm
Labels: enhancement

#3643 (plugin) apps::protocols::cifs - new
  apps/protocols/cifs/custom/libcifs.pm
  apps/protocols/cifs/mode/connection.pm
  apps/protocols/cifs/mode/filescount.pm
  apps/protocols/cifs/mode/filesdate.pm
  apps/protocols/cifs/mode/scenario.pm
  apps/protocols/cifs/plugin.pm
Labels: new

#3644 (plugin) network::silverpeak::snmp - better date management
  network/silverpeak/snmp/mode/alarms.pm
  network/silverpeak/snmp/mode/status.pm
  network/silverpeak/snmp/mode/uptime.pm
  network/silverpeak/snmp/plugin.pm
Labels: bug

#3647 (plugin) apps::monitoring::netdata::restapi - mode load add option --…
  apps/monitoring/netdata/restapi/mode/load.pm
Labels: enhancement

#3648 (plugin) os::windows::wsman - add eventlog mode
  os/windows/wsman/mode/eventlog.pm
  os/windows/wsman/plugin.pm
Labels: enhancement

#3649 (plugin) network::cambium::epmp::snmp - add cambium SNMP plugin
  network/cambium/epmp/snmp/mode/antenna.pm
  network/cambium/epmp/snmp/mode/cpu.pm
  network/cambium/epmp/snmp/mode/interfaces.pm
  network/cambium/epmp/snmp/mode/license.pm
  network/cambium/epmp/snmp/mode/uptime.pm
  network/cambium/epmp/snmp/plugin.pm
Labels: new

#3652 (plugin) apps::protocols::cifs - add mode files-size
  apps/protocols/cifs/custom/libcifs.pm
  apps/protocols/cifs/mode/filessize.pm
  apps/protocols/cifs/plugin.pm
Labels: enhancement

#3658 (plugin) apps::monitoring::kadiska - apply suggestions
  apps/monitoring/kadiska/mode/listtargets.pm
  apps/monitoring/kadiska/mode/nettracerstatistics.pm
  apps/monitoring/kadiska/mode/watcherstatistics.pm
  apps/monitoring/kadiska/plugin.pm
Labels: enhancement

#3659 (plugin) cloud::prometheus::exporters::cadvisor - mode memory fix uni…
  cloud/prometheus/exporters/cadvisor/mode/memory.pm
Labels: bugfix

#3660 (plugin) os::windows::local - harden regexp source
  os/windows/local/mode/ntp.pm
Labels: enhancement

#3661 (plugin) network::cisco::meraki::cloudcontroller::restapi - mode devi…
  network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
Labels: bugfix

#3663 (plugin) apps::ceph::restapi - new
  apps/ceph/restapi/custom/api.pm
  apps/ceph/restapi/mode/health.pm
  apps/ceph/restapi/mode/listpools.pm
  apps/ceph/restapi/mode/osd.pm
  apps/ceph/restapi/mode/pools.pm
  apps/ceph/restapi/plugin.pm
Labels: new

#3664 (plugin) cloud::azure::* curl is now the default backend for Azure Packs
  cloud/azure/custom/api.pm
Labels: enhancement

#2709 (plugin) apps::protocols::tcp - add responsetime mode and rename existing one into connectionstatus
  apps/protocols/tcp/mode/connectionstatus.pm
  apps/protocols/tcp/mode/responsetime.pm
  apps/protocols/tcp/plugin.pm
Labels: enhancement

#3669 (plugin) apps::protocols::tcp - force perfdata v2
  apps/protocols/tcp/mode/connectionstatus.pm
  apps/protocols/tcp/mode/responsetime.pm
  apps/protocols/tcp/plugin.pm
Labels: breaking change

#3670 (plugin) apps::checkmyws - removed
  apps/checkmyws/mode/status.pm
  apps/checkmyws/plugin.pm
Labels: breaking change

#3672 (plugin) cloud::prometheus::exporters::nodeexporter - fix storage met…
  cloud/prometheus/exporters/nodeexporter/mode/storage.pm
  cloud/prometheus/exporters/nodeexporter/plugin.pm
  cloud/prometheus/restapi/custom/api.pm
Labels: bugfix

#3665 (plugin) apps::proxmox::ve::restapi - add filtering capabilities to s…
  apps/proxmox/ve/restapi/custom/api.pm
  apps/proxmox/ve/restapi/mode/nodeusage.pm
  apps/proxmox/ve/restapi/mode/storageusage.pm
  apps/proxmox/ve/restapi/mode/version.pm
  apps/proxmox/ve/restapi/mode/vmusage.pm
  apps/proxmox/ve/restapi/plugin.pm
Labels: enhancement

#3676 (plugin) apps::proxmox::ve::restapi - metric v2 + discovery mode
  apps/proxmox/ve/restapi/mode/discovery.pm
  apps/proxmox/ve/restapi/mode/listvms.pm
  apps/proxmox/ve/restapi/mode/nodeusage.pm
  apps/proxmox/ve/restapi/mode/storageusage.pm
  apps/proxmox/ve/restapi/mode/vmusage.pm
  apps/proxmox/ve/restapi/plugin.pm
Labels: enhancement

#3674 (plugin) [network::cisco::meraki::cloudcontroller::restapi::plugin] - Add filter option for swicth port
  network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
Labels: enhancement

#3677 (plugin) apps::protocols::cifs - connection error
  apps/protocols/cifs/mode/connection.pm
Labels: bugfix

#3679 (plugin) storage::hp::storeonce::restapi - renamed to storage::hp::st…
  storage/hp/storeonce/3/restapi/custom/api.pm
  storage/hp/storeonce/3/restapi/mode/clusterusage.pm
  storage/hp/storeonce/3/restapi/mode/fcsusage.pm
  storage/hp/storeonce/3/restapi/mode/nasusage.pm
  storage/hp/storeonce/3/restapi/mode/servicesetusage.pm
  storage/hp/storeonce/3/restapi/plugin.pm
Labels: breaking change

#3680 (plugin) network::stormshield::snmp - handle vpn new mib
  network/stormshield/snmp/mode/vpnstatus.pm
Labels: enhancement

#3681 (plugin) network::f5::bigip::snmp - change error message if no entrie…
  network/f5/bigip/snmp/mode/nodestatus.pm
Labels: enhancement

#3682 (plugin) storage::hp::storeonce::4::restapi - new
  storage/hp/storeonce/4/restapi/custom/api.pm
  storage/hp/storeonce/4/restapi/mode/appliances.pm
  storage/hp/storeonce/4/restapi/mode/components/drive.pm
  storage/hp/storeonce/4/restapi/mode/components/driveencl.pm
  storage/hp/storeonce/4/restapi/mode/components/fan.pm
  storage/hp/storeonce/4/restapi/mode/components/iomodule.pm
  storage/hp/storeonce/4/restapi/mode/components/pool.pm
  storage/hp/storeonce/4/restapi/mode/components/psu.pm
  storage/hp/storeonce/4/restapi/mode/components/temperature.pm
  storage/hp/storeonce/4/restapi/mode/hardwarestorage.pm
  storage/hp/storeonce/4/restapi/mode/listappliances.pm
  storage/hp/storeonce/4/restapi/mode/liststores.pm
  storage/hp/storeonce/4/restapi/mode/stores.pm
  storage/hp/storeonce/4/restapi/plugin.pm
Labels: new

#3683 (plugin) storage::ibm::storwize::ssh - pool-usage illegal division by…
  storage/ibm/storwize/ssh/mode/poolusage.pm
Labels: bugfix

#3684 (plugin) apps::ipfabric - add snapshot id param
  apps/ipfabric/custom/api.pm
  apps/ipfabric/mode/discovery.pm
  apps/ipfabric/mode/pathverification.pm
Labels: enhancement

#3685 (plugin) cloud::azure::network::trafficmanager - fix help and metric label
  cloud/azure/network/trafficmanager/mode/endpointstatus.pm
  cloud/azure/network/trafficmanager/mode/queries.pm
Labels: enhancement

#3688 (plugin) cloud::aws::backup - fix mode name for compliance
  cloud/aws/backup/plugin.pm
Labels: enhancement

#3694 (plugin) os::linux::local - mode cpu wrong calculation
  os/linux/local/mode/cpu.pm
Labels: bugfix

#3695 (mode) snmp_standard::mode::storage - add option --path-best-match
  snmp_standard/mode/storage.pm
Labels: enhancement

#3696 (plugin) network::dell::nseries::snmp - metric v2 + renamed dell::n4000
  centreon/common/dell/fastpath/snmp/mode/components/fan.pm
  centreon/common/dell/fastpath/snmp/mode/components/psu.pm
  centreon/common/dell/fastpath/snmp/mode/components/temperature.pm
  centreon/common/dell/fastpath/snmp/mode/cpu.pm
  centreon/common/dell/fastpath/snmp/mode/environment.pm
  centreon/common/dell/fastpath/snmp/mode/memory.pm
  network/dell/nseries/snmp/mode/interfaces.pm
  network/dell/nseries/snmp/mode/time.pm
  network/dell/nseries/snmp/mode/uptime.pm
  network/dell/nseries/snmp/plugin.pm
Labels: enhancement, breaking change

#3587 (plugin) storage::netapp::ontap - add aggregates mode
  storage/netapp/ontap/restapi/mode/aggregates.pm
  storage/netapp/ontap/restapi/plugin.pm
Labels: enhancement

#3699 (plugin) network::libraesva::snmp - mode system fix metric name
  network/libraesva/snmp/mode/system.pm
Labels: bugfix

#3700 (plugin) storage::emc::xtremio::restapi - add modes dpg and storage-c…
  storage/emc/xtremio/restapi/custom/xtremioapi.pm
  storage/emc/xtremio/restapi/mode/dpg.pm
  storage/emc/xtremio/restapi/mode/storagecontrollers.pm
  storage/emc/xtremio/restapi/plugin.pm
Labels: enhancement
