Repository centreon/centreon-plugins, pull requests merged in 2022-04, with the labels that each got.

#3575 (plugin) hardware::server::hp::proliant::snmp - memory component error
  hardware/server/hp/proliant/snmp/mode/components/ilo.pm
  hardware/server/hp/proliant/snmp/mode/components/memory.pm
Labels: bug

#3576 (plugin) network::oneaccess::snmp - add mode cells-radio
  network/oneaccess/snmp/mode/cellsradio.pm
  network/oneaccess/snmp/mode/cpu.pm
  network/oneaccess/snmp/mode/interfaces.pm
  network/oneaccess/snmp/mode/memory.pm
  network/oneaccess/snmp/plugin.pm
Labels: mode

#3578 (plugin) os::windows::local - harden regexp
  os/windows/local/mode/ntp.pm
Labels: enhancement

#3582 (custom) cloud::aws::custom::awscli - adding AssumeRole auth for awscli
  cloud/aws/custom/awscli.pm
Labels: enhancement

#3579 (lib) centreon::plugin::http - Typo uninitialized value
  centreon/plugins/http.pm
Labels: fix

#3586 (cloud::google::gcp) discovery failed empty results
  cloud/google/gcp/cloudsql/mysql/mode/discovery.pm
  cloud/google/gcp/compute/computeengine/mode/discovery.pm
  cloud/google/gcp/storage/mode/discovery.pm
Labels: bug

#3590 (plugin) network::nortel::standard::snmp - incorrect temperature
  network/nortel/standard/snmp/mode/components/temperature.pm
Labels: bug

#3594 (plugin) cloud::aws::elb::network - fix namespace in targetshealth mode and add target-group dimension
  cloud/aws/elb/network/mode/targetshealth.pm
Labels: fix

#3583 (plugin): virtualization-nutanix-snmp - Nutanix host discovery & metrics v2
  cloud/nutanix/snmp/mode/clusterusage.pm
  cloud/nutanix/snmp/mode/containerusage.pm
  cloud/nutanix/snmp/mode/discovery.pm
  cloud/nutanix/snmp/mode/diskusage.pm
  cloud/nutanix/snmp/mode/hypervisorusage.pm
  cloud/nutanix/snmp/mode/storagepoolusage.pm
  cloud/nutanix/snmp/mode/vmusage.pm
  cloud/nutanix/snmp/plugin.pm
Labels: enhancement, plugin

#3597 (plugin) virtualization-nutanix-snmp - fix typo in storagepools.pm
  cloud/nutanix/snmp/mode/storagepoolusage.pm
Labels: fix

#3599 (plugin) cloud::cadvisor::restapi - manage cgroupv2 api
  cloud/cadvisor/restapi/custom/api.pm
  cloud/cadvisor/restapi/mode/containerusage.pm
Labels: enhancement

#3600 (plugin) hardware::pdu::cyberpower::snmp - add ampere perfdata even if 0
  hardware/pdu/cyberpower/snmp/mode/outlets.pm
Labels: enhancement

#3601 (plugin) cloud::aws::elb - add ARN in host disco output for ELB app and network
  cloud/aws/elb/application/mode/connections.pm
  cloud/aws/elb/application/mode/discovery.pm
  cloud/aws/elb/application/mode/httpcodes.pm
  cloud/aws/elb/application/mode/targetshealth.pm
  cloud/aws/elb/network/mode/discovery.pm
Labels: enhancement

#3608 (plugin) apps::monitoring::ntopng::restapi - initial
  apps/monitoring/ntopng/restapi/custom/api.pm
  apps/monitoring/ntopng/restapi/mode/alerts.pm
  apps/monitoring/ntopng/restapi/mode/hostflows.pm
  apps/monitoring/ntopng/restapi/mode/netflowhealth.pm
  apps/monitoring/ntopng/restapi/mode/probehealth.pm
  apps/monitoring/ntopng/restapi/plugin.pm
Labels: new

#3618 (plugin) database::mssql - fix list-databases undefined value
  database/mssql/mode/listdatabases.pm
Labels: bug

#3620 (plugin) notification::centreon::opentickets::api
  notification/centreon/opentickets/api/custom/api.pm
  notification/centreon/opentickets/api/mode/openhost.pm
  notification/centreon/opentickets/api/mode/openservice.pm
  notification/centreon/opentickets/api/plugin.pm
Labels: new

#3623 (plugin) apps::backup::backupexec::local - new
  apps/backup/backupexec/local/mode/alerts.pm
  apps/backup/backupexec/local/mode/disks.pm
  apps/backup/backupexec/local/mode/jobs.pm
  apps/backup/backupexec/local/mode/listdisks.pm
  apps/backup/backupexec/local/mode/resources/types.pm
  apps/backup/backupexec/local/plugin.pm
  centreon/common/powershell/backupexec/alerts.pm
  centreon/common/powershell/backupexec/disks.pm
  centreon/common/powershell/backupexec/functions.pm
  centreon/common/powershell/backupexec/jobs.pm
Labels: new

#3624 (plugin) apps::backup::backupexec::local - fix disk perfdata
  apps/backup/backupexec/local/mode/disks.pm
Labels: new
