Repository centreon/centreon-plugins, pull requests merged in 2022-11, with the labels that each got.

#4022 (plugin) network::enterasys::snmp - new
  network/enterasys/snmp/mode/cpu.pm
  network/enterasys/snmp/mode/interfaces.pm
  network/enterasys/snmp/mode/memory.pm
  network/enterasys/snmp/mode/storage.pm
  network/enterasys/snmp/mode/uptime.pm
  network/enterasys/snmp/plugin.pm
Labels: new

#4031 (plugin) cloud::azure::storageaccount - enhancing fileshare monitoring mode, addi list fileshare
  cloud/azure/classicstorage/storageaccount/plugin.pm
  cloud/azure/common/storageaccount/filesharequota.pm
  cloud/azure/common/storageaccount/listfileshares.pm
  cloud/azure/custom/api.pm
  cloud/azure/storage/storageaccount/plugin.pm
Labels: enhancement

#4037 (plugin) apps::monitoring::kadiska::watcherstatistics - fixing function name
  apps/monitoring/kadiska/mode/watcherstatistics.pm
Labels: bugfix

#4041 (plugin) storage::netapp:ontap::restapi - fix missing counters for space usage and bug in listvolumes
  storage/netapp/ontap/restapi/mode/aggregates.pm
  storage/netapp/ontap/restapi/mode/listvolumes.pm
Labels: bugfix

#4045 (plugin) cloud::aws::cloudwatch::discovery - removing VPC and DynamoDB discovery
  cloud/aws/cloudwatch/mode/discovery.pm
Labels: bugfix

#4047 (plugin) os::windows::wsman - mode storages fix illegal division by zero
  os/windows/wsman/mode/storages.pm
Labels: bugfix

#4048 snmp standard interfaces - some equipments can have the value 0 for a…
  snmp_standard/mode/interfaces.pm
  snmp_standard/mode/listinterfaces.pm
Labels: bugfix

#4043 (plugin) hardware::server::xfusion::ibmc::snmp::plugin - Add xFusion iBMC snmp monitoring
  hardware/server/xfusion/ibmc/snmp/mode/components/component.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/cpu.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/fan.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/harddisk.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/logicaldrive.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/memory.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/pcie.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/psu.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/raidcontroller.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/temperature.pm
  hardware/server/xfusion/ibmc/snmp/mode/hardware.pm
  hardware/server/xfusion/ibmc/snmp/plugin.pm
Labels: new

#4049 (plugin) hardware::server::xfusion::ibmc::snmp - force metric v2
  hardware/server/xfusion/ibmc/snmp/mode/components/component.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/cpu.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/fan.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/harddisk.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/logicaldrive.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/memory.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/pcie.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/psu.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/raidcontroller.pm
  hardware/server/xfusion/ibmc/snmp/mode/components/temperature.pm
  hardware/server/xfusion/ibmc/snmp/mode/hardware.pm
  hardware/server/xfusion/ibmc/snmp/plugin.pm
Labels: enhancement

#4027 (plugin) cloud::azure::datafactory::factories - add new plugin
  cloud/azure/datafactory/factories/mode/discovery.pm
  cloud/azure/datafactory/factories/mode/factoryusage.pm
  cloud/azure/datafactory/factories/mode/integrationruntime.pm
  cloud/azure/datafactory/factories/plugin.pm
Labels: new

#4053 (plugin) hardware::ups::himoinsa::snmp::plugin - new
  hardware/ups/himoinsa/snmp/mode/frequency.pm
  hardware/ups/himoinsa/snmp/mode/fuellevel.pm
  hardware/ups/himoinsa/snmp/mode/phase.pm
  hardware/ups/himoinsa/snmp/mode/status.pm
  hardware/ups/himoinsa/snmp/mode/uptime.pm
  hardware/ups/himoinsa/snmp/mode/voltage.pm
  hardware/ups/himoinsa/snmp/plugin.pm
Labels: enhancement, new

#4058 prepare release 20221115
  changelog
Labels: enhancement

#4060 (plugin) cloud::aws::elasticache - Add Host Discovery rules to AWS Elasticache
  cloud/aws/elasticache/mode/discovery.pm
  cloud/aws/elasticache/plugin.pm
Labels: enhancement

#4064 (plugin) hardware::ups::apc::snmp - mode battery-status add time on b…
  hardware/ups/apc/snmp/mode/batterystatus.pm
Labels: enhancement

#4081 (plugin) apps::protocols::imap - fix port
  apps/protocols/imap/custom/imapclient.pm
Labels: bugfix

#4077 (plugin) network::patton::smartnode::snmp - new
  network/patton/smartnode/snmp/mode/call.pm
  network/patton/smartnode/snmp/mode/system.pm
  network/patton/smartnode/snmp/plugin.pm
Labels: new
