Repository centreon/centreon-plugins, pull requests merged in 2022-03, with the labels that each got.

#3514 (plugin) network::fiberstore::snmp - harden memory mode check
  network/fiberstore/snmp/mode/memory.pm
Labels: enhancement

#3515 (plugin) cloud::aws::cloudwatch - remove required option --dimension
  cloud/aws/cloudwatch/mode/getmetrics.pm
Labels: enhancement

#3516 (core) add --debug-stream option
  centreon/plugins/output.pm
Labels: enhancement

#3517 (plugin) apps::microsoft::hyperv::2012 - node-replication health no m…
  apps/microsoft/hyperv/2012/local/mode/nodereplication.pm
  apps/microsoft/hyperv/2012/local/mode/resources/types.pm
Labels: bug

#3521 (collection) add methods capture and scientific2number
  apps/protocols/http/mode/collection.pm
  apps/protocols/snmp/mode/collection.pm
  centreon/common/protocols/sql/mode/collection.pm
Labels: enhancement

#3522 (plugin) cloud::prometheus::direct::kubernetes - node-status mode use wrong status
  cloud/prometheus/direct/kubernetes/mode/nodestatus.pm
Labels: bug

#3525 (plugin) apps::microsoft::hyperv::2012 - try to load Hyper-V module i…
  centreon/common/powershell/hyperv/2012/listnodevms.pm
  centreon/common/powershell/hyperv/2012/nodeintegrationservice.pm
  centreon/common/powershell/hyperv/2012/nodereplication.pm
  centreon/common/powershell/hyperv/2012/nodesnapshot.pm
  centreon/common/powershell/hyperv/2012/nodevmstatus.pm
Labels: enhancement

#3526 (plugin) apps::protocols::nrpe - remove basic and credentials options
  apps/protocols/nrpe/custom/nsclient.pm
Labels: enhancement

#3527 (plugin) hardware::server::hp::ilo::xmlapi - add option --force-ilo2 …
  hardware/server/hp/ilo/xmlapi/custom/api.pm
Labels: enhancement

#3528 (plugin) apps::protocols::nrpe - set nsclient api timeout to 50sec
  apps/protocols/nrpe/custom/nsclient.pm
Labels: enhancement

#3529 (plugin) apps::microsoft::hyperv::2012::local - some cleaning
  apps/microsoft/hyperv/2012/local/mode/nodeintegrationservice.pm
  apps/microsoft/hyperv/2012/local/mode/nodesnapshot.pm
  apps/microsoft/hyperv/2012/local/mode/nodevmstatus.pm
  apps/microsoft/hyperv/2012/local/mode/scvmmintegrationservice.pm
  apps/microsoft/hyperv/2012/local/mode/scvmmsnapshot.pm
  apps/microsoft/hyperv/2012/local/mode/scvmmvmstatus.pm
Labels: enhancement

#3535 (plugin) hardware::server::hp::ilo::xmlapi - harden xml check response
  hardware/server/hp/ilo/xmlapi/custom/api.pm
Labels: enhancement

#3446 (plugin) cloud::azure::network::trafficmanager - new plugin
  cloud/azure/network/trafficmanager/mode/discovery.pm
  cloud/azure/network/trafficmanager/mode/endpointstatus.pm
  cloud/azure/network/trafficmanager/mode/health.pm
  cloud/azure/network/trafficmanager/mode/queries.pm
  cloud/azure/network/trafficmanager/plugin.pm
Labels: new

#3536 (plugin) hardware::server::hp::ilo::restapi - trailing slash
  centreon/common/redfish/restapi/mode/hardware.pm
Labels: enhancement

#3538 (plugin) apps::mq::activemq::jmx - add brokers status
  apps/mq/activemq/jmx/mode/brokers.pm
Labels: enhancement

#3539 (plugin) network::dlink::standard::snmp - mode hardware unitialized s…
  network/dlink/standard/snmp/mode/components/fan.pm
Labels: bug

#3540 (plugin) apps::backup::arcserve::udp::mssql - use UTC times
  apps/backup/arcserve/udp/mssql/mode/jobstatus.pm
Labels: enhancement

#3541 (core) add debug snmp
  centreon/plugins/snmp.pm
Labels: enhancement

#3542 (plugin) storage::emc::DataDomain - mode filesystem illegal division
  storage/emc/DataDomain/mode/filesystem.pm
Labels: bug

#3545 (plugin) apps::vmware::connector - mode datastore-iops negative values
  apps/vmware/connector/mode/datastoreiops.pm
Labels: enhancement

#3549 (plugin) database::mssql - mode databases-size sql request
  database/mssql/mode/databasessize.pm
Labels: bug

#3485 (plugin) apps::pvx::restapi - add default-value parameter
  apps/pvx/restapi/custom/api.pm
Labels: enhancement

#3563 (plugin) network::citrix::netscaler::snmp::mode::connections - add established counter
  network/citrix/netscaler/snmp/mode/connections.pm
Labels: enhancement

#3559 (plugin) cloud::azure::database::mariadb - add new plugin
  cloud/azure/database/mariadb/mode/connections.pm
  cloud/azure/database/mariadb/mode/cpu.pm
  cloud/azure/database/mariadb/mode/discovery.pm
  cloud/azure/database/mariadb/mode/ioconsumption.pm
  cloud/azure/database/mariadb/mode/memory.pm
  cloud/azure/database/mariadb/mode/queries.pm
  cloud/azure/database/mariadb/mode/replication.pm
  cloud/azure/database/mariadb/mode/storage.pm
  cloud/azure/database/mariadb/mode/traffic.pm
  cloud/azure/database/mariadb/plugin.pm
Labels: new

#3565 (plugin) cloud::aws::fsx - Fix discovery mode
  cloud/aws/fsx/mode/discovery.pm
Labels: fix

#3569 (collection) use all variables in thresholds attributes
  apps/protocols/http/mode/collection.pm
  apps/protocols/snmp/mode/collection.pm
  centreon/common/protocols/sql/mode/collection.pm
Labels: enhancement

#3570 (plugin) storage::dell::powerstore::restapi - mode alerts add acknowl…
  storage/dell/powerstore/restapi/mode/alerts.pm
Labels: enhancement
