Repository centreon/centreon-plugins, pull requests merged in 2022-09, with the labels that each got.

#3874 (plugin) network::oneaccess::snmp - add rtt-probes mode
  network/oneaccess/snmp/mode/cellsradio.pm
  network/oneaccess/snmp/mode/listrttprobes.pm
  network/oneaccess/snmp/mode/rttprobes.pm
  network/oneaccess/snmp/plugin.pm
Labels: enhancement

#3875 (plugin) storage::dell::me4::restapi - add --digest-sha256 option
  storage/dell/me4/restapi/custom/api.pm
Labels: enhancement

#3877 (plugin) network::cisco::standard::snmp - mode environment add option…
  centreon/common/cisco/standard/snmp/mode/components/psu.pm
  centreon/common/cisco/standard/snmp/mode/environment.pm
Labels: enhancement

#3876 plugin) os::linux::local - change snmp discovery extra-oids format
  os/linux/local/mode/discoverysnmp.pm
  os/linux/local/mode/discoverysnmpv3.pm
Labels: enhancement

#3866 (plugin) cloud::azure::managemement::budgets - Add cost management plugin
  cloud/azure/custom/api.pm
  cloud/azure/management/costs/mode/budgets.pm
  cloud/azure/management/costs/plugin.pm
Labels: new

#3880 (plugin) storage::emc::vplex::restapi - handle api v2
  storage/emc/vplex/restapi/custom/apiv1.pm
  storage/emc/vplex/restapi/custom/apiv2.pm
  storage/emc/vplex/restapi/custom/vplexapi.pm
  storage/emc/vplex/restapi/mode/clustercommunication.pm
  storage/emc/vplex/restapi/mode/clusterdevices.pm
  storage/emc/vplex/restapi/mode/directors.pm
  storage/emc/vplex/restapi/mode/distributeddevices.pm
  storage/emc/vplex/restapi/mode/fans.pm
  storage/emc/vplex/restapi/mode/psus.pm
  storage/emc/vplex/restapi/mode/storagevolumes.pm
  storage/emc/vplex/restapi/plugin.pm
Labels: enhancement

#3881 (plugin) storage::emc::vplex::restapi - default backend curl
  storage/emc/vplex/restapi/custom/apiv1.pm
  storage/emc/vplex/restapi/custom/apiv2.pm
Labels: enhancement

#3879 (plugin) apps::monitoring::openmetrics - Getting rid of single quote in instance filter (scrapemetrics.pm)
  apps/monitoring/openmetrics/mode/scrapemetrics.pm
Labels: bugfix

#3884 (plugin) cloud::azure::recovery::backupjobstatus - fix bug on loopback option
  cloud/azure/management/recovery/mode/backupjobsstatus.pm
Labels: bugfix

#3887 (plugin) cloud::azure::management::costs - add list-budget mode
  cloud/azure/custom/api.pm
  cloud/azure/management/costs/mode/budgets.pm
  cloud/azure/management/costs/mode/listbudgets.pm
  cloud/azure/management/costs/plugin.pm
Labels: enhancement

#3898 (plugin) os::linux::local - mode uptime handle login message
  os/linux/local/mode/uptime.pm
Labels: enhancement

#3878 prepare release 20220913
  changelog
Labels: documentation

#3900 (plugin) os::linux::local::mode::pendingupdates - adding pending security updates metric
  os/linux/local/mode/pendingupdates.pm
Labels: enhancement

#3905 (plugin) cloud::nutanix::snmp - remove characters
  cloud/nutanix/snmp/mode/diskusage.pm
  cloud/nutanix/snmp/mode/listdisks.pm
Labels: bugfix

#3902 Fix filter-active-status option type
  os/as400/connector/mode/jobs.pm
Labels: bug

#3906 (plugin) cloud::docker::restapi - mode container-usage add option --a…
  cloud/docker/restapi/custom/api.pm
  cloud/docker/restapi/mode/containerusage.pm
Labels: enhancement

#3907 (plugin) storage::hp::p2000::xmlapi - add --digest-sha256 option
  storage/hp/p2000/xmlapi/custom/api.pm
Labels: enhancement

#3908 (plugin) cloud::docker::restapi - mode container-usage add option --n…
  cloud/docker/restapi/custom/api.pm
  cloud/docker/restapi/mode/containerusage.pm
Labels: enhancement

#3909 (plugin) cloud::docker::restapi - mode container-usage add option --n…
  cloud/docker/restapi/mode/containerusage.pm
Labels: enhancement

#3910 (plugin) storage::netapp::ontap::restapi - mode volumes usage space c…
  storage/netapp/ontap/restapi/mode/volumes.pm
Labels: bugfix

#3911 (plugin) hardware::server::hp::ilo::xmlapi - add decode option working
  hardware/server/hp/ilo/xmlapi/custom/api.pm
Labels: enhancement

#3913 (plugin) network::aruba::orchestrator::restapi - new
  network/aruba/orchestrator/restapi/custom/api.pm
  network/aruba/orchestrator/restapi/mode/alarms.pm
  network/aruba/orchestrator/restapi/mode/appliances.pm
  network/aruba/orchestrator/restapi/mode/discovery.pm
  network/aruba/orchestrator/restapi/plugin.pm
Labels: new

#3916 Enhance --wsman-debug option
  centreon/plugins/wsman.pm
Labels: enhancement

#3919 (plugin) network::cisco::meraki::cloudcontroller::restapi - handle li…
  network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
Labels: enhancement

#3914 (plugin) hardware::ups::socomec::netvision - netvision v5 supported
  hardware/ups/socomec/netvision/snmp/mode/alarms.pm
  hardware/ups/socomec/netvision/snmp/mode/battery.pm
  hardware/ups/socomec/netvision/snmp/mode/inputlines.pm
  hardware/ups/socomec/netvision/snmp/mode/outputlines.pm
  hardware/ups/socomec/netvision/snmp/plugin.pm
Labels: enhancement

#3921 (dbi) add --exec-timeout option
  centreon/plugins/dbi.pm
Labels: enhancement

#3926 (plugin) network::aruba::orchestrator::restapi - fix group endpoint
  network/aruba/orchestrator/restapi/mode/appliances.pm
  network/aruba/orchestrator/restapi/mode/discovery.pm
Labels: enhancement

#3924 (plugin) apps::protocols::imap - new imap library
  apps/protocols/imap/custom/imapclient.pm
  apps/protocols/imap/lib/imap.pm
  apps/protocols/imap/mode/login.pm
  apps/protocols/imap/mode/searchmessage.pm
  apps/protocols/imap/plugin.pm
  apps/redis/sentinel/custom/cli.pm
Labels: enhancement, breaking change

#3928 (plugin) network::aruba::orchestrator::restapi - fix filter-hostname …
  network/aruba/orchestrator/restapi/mode/alarms.pm
  network/aruba/orchestrator/restapi/mode/appliances.pm
Labels: bugfix

#3929 (plugin) network::alcatel::omniswitch::snmp - add mode virtual-chassis
  network/alcatel/omniswitch/snmp/mode/virtualchassis.pm
  network/alcatel/omniswitch/snmp/plugin.pm
Labels: enhancement

#3923 (contrib) Everything your grandma needs to know to write a plugin and a mode
  contrib/tutorial/apps/myawesomeapp/api/mode/appmetrics.pm
  contrib/tutorial/apps/myawesomeapp/api/plugin.pm
Labels: documentation

#3930 (plugin) cloud::docker::restapi - mode container-usage fix cpu stats
  cloud/docker/restapi/mode/containerusage.pm
Labels: bugfix

#3931 (plugin) apps::centreon::sql - mode count-services add by status
  apps/centreon/sql/mode/countservices.pm
Labels: enhancement

#3933 (plugin) network::brocade::snmp - use new perfdata
  network/brocade/snmp/mode/cpu.pm
  network/brocade/snmp/mode/hardware.pm
  network/brocade/snmp/mode/interfaces.pm
  network/brocade/snmp/mode/memory.pm
Labels: enhancement, breaking change

#3935 (core) add alert_triggered() method for option --filter-perfdata-adv
  centreon/plugins/misc.pm
  centreon/plugins/output.pm
  centreon/plugins/perfdata.pm
Labels: enhancement

#3937 (windows) add mode updates
  centreon/common/powershell/windows/updates.pm
  os/windows/local/mode/updates.pm
  os/windows/local/plugin.pm
  os/windows/wsman/mode/updates.pm
  os/windows/wsman/plugin.pm
Labels: enhancement, mode

#3938 (core) can use variable to defined unitary options
  centreon/plugins/alternative/Getopt.pm
Labels: enhancement

#3934 (plugin) network::checkpoint::snmp - mode vsx add active connections …
  network/checkpoint/snmp/mode/vsx.pm
Labels: enhancement

#3939 (plugin) network::citrix::netscaler::snmp - mode vserver-status skip …
  network/citrix/netscaler/snmp/mode/vserverstatus.pm
Labels: bugfix

#3941 (plugin) os::linux::local - mode traffic add option --guess-speed
  os/linux/local/mode/traffic.pm
Labels: enhancement

#3943 (snmp) cpu standard mode add option --use-ucd
  snmp_standard/mode/cpu.pm
Labels: enhancement

#3936 (plugin) storage::hp::p2000::xmlapi - mode health fix Not an ARRAY re…
  storage/hp/p2000/xmlapi/custom/api.pm
  storage/hp/p2000/xmlapi/mode/components/fan.pm
  storage/hp/p2000/xmlapi/mode/components/fru.pm
  storage/hp/p2000/xmlapi/mode/components/psu.pm
  storage/hp/p2000/xmlapi/mode/components/sensor.pm
Labels: bugfix

#3945 (plugin) network::hp::procurve::snmp - mode interfaces add optical me…
  network/hp/procurve/snmp/mode/interfaces.pm
Labels: enhancement
