Repository centreon/centreon-plugins, pull requests merged in 2022-07, with the labels that each got.

#3758 (plugin) cloud::azure::database::mysql - Fix typo in serverlog-usage option label
  cloud/azure/database/mysql/mode/storage.pm
Labels: bugfix

#3768 (plugin) storage::hp::p2000::xmlapi - fix saslink count perfdata
  storage/hp/p2000/xmlapi/mode/components/saslink.pm
Labels: bugfix

#3769 (mode) snmp_standard::mode::stringvalue - fix infinite loop
  snmp_standard/mode/stringvalue.pm
Labels: bugfix

#3771 (plugin) database::postgres - metrics v2 + mode bloat
  database/postgres/mode/backends.pm
  database/postgres/mode/bloat.pm
  database/postgres/mode/connectiontime.pm
  database/postgres/mode/databasesize.pm
  database/postgres/mode/hitratio.pm
  database/postgres/mode/locks.pm
  database/postgres/mode/querytime.pm
  database/postgres/mode/statistics.pm
  database/postgres/mode/timesync.pm
  database/postgres/mode/vacuum.pm
  database/postgres/plugin.pm
Labels: enhancement, breaking change

#3767 (plugin) apps::monitoring::nodeexporter - adding plugin to monitor host through node exporter metrics
  apps/monitoring/nodeexporter/mode/cpu.pm
  apps/monitoring/nodeexporter/mode/listinterfaces.pm
  apps/monitoring/nodeexporter/mode/liststorages.pm
  apps/monitoring/nodeexporter/mode/load.pm
  apps/monitoring/nodeexporter/mode/memory.pm
  apps/monitoring/nodeexporter/mode/storage.pm
  apps/monitoring/nodeexporter/mode/traffic.pm
  apps/monitoring/nodeexporter/plugin.pm
Labels: new

#3773 (plugin) database::postgres - mode bloat fix metric name
  database/postgres/mode/bloat.pm
Labels: enhancement

#3774 (plugin) apps::monitoring::linux::nodeexporter - correct paths and disco keys name
  apps/monitoring/nodeexporter/linux/mode/cpu.pm
  apps/monitoring/nodeexporter/linux/mode/listinterfaces.pm
  apps/monitoring/nodeexporter/linux/mode/liststorages.pm
  apps/monitoring/nodeexporter/linux/mode/load.pm
  apps/monitoring/nodeexporter/linux/mode/memory.pm
  apps/monitoring/nodeexporter/linux/mode/storage.pm
  apps/monitoring/nodeexporter/linux/mode/traffic.pm
  apps/monitoring/nodeexporter/linux/plugin.pm
Labels: enhancement

#3778 (plugin) cloud::aws::ec2::plugin - adding platform details in discovery output
  cloud/aws/ec2/mode/discovery.pm
Labels: enhancement

#3781 (plugin) cloud::prometheus::restapi - adding discovery mode for Prometheus targets
  cloud/prometheus/restapi/mode/discovery.pm
  cloud/prometheus/restapi/plugin.pm
Labels: enhancement

#3784 apps::monitoring::ekara - remove some perfdata and force curl backend
  apps/monitoring/iplabel/ekara/restapi/custom/api.pm
  apps/monitoring/iplabel/ekara/restapi/mode/incidents.pm
Labels: enhancement

#3779 (plugin) ceph::restapi -- add 'Accept: application/vnd.ceph.api.v1.0+json' header
  apps/ceph/restapi/custom/api.pm
Labels: enhancement

#3782 apps::protocols::http::mode::jsoncontent - perfdata missing when node value is negative
  apps/protocols/http/mode/jsoncontent.pm
Labels: bugfix

#3786 (plugin) storage::hp::storeonce::4::restapi - mode hardware-storage a…
  storage/hp/storeonce/4/restapi/mode/hardwarestorage.pm
Labels: enhancement

#3787 (core) add option --change-long-output
  centreon/plugins/output.pm
Labels: enhancement

#3788 (plugin) network::aruba::aoscx::snmp - fix temperature value
  network/aruba/aoscx/snmp/mode/components/fan.pm
  network/aruba/aoscx/snmp/mode/components/psu.pm
  network/aruba/aoscx/snmp/mode/components/temperature.pm
Labels: bugfix

#3790 (plugin) apps::vmware::connector - mode discovery add tags option
  apps/vmware/connector/mode/discovery.pm
Labels: enhancement

#3792 (plugin) apps::protocols::http - mode collection add filter option fo…
  apps/protocols/http/mode/collection.pm
  centreon/common/protocols/sql/mode/collection.pm
Labels: enhancement

#3793 network::alcatel::oxe::snmp - add new metrics to domain check & add new trunk usage mode
  network/alcatel/oxe/snmp/mode/domains.pm
  network/alcatel/oxe/snmp/mode/trunks.pm
  network/alcatel/oxe/snmp/plugin.pm
Labels: enhancement
