Repository centreon/centreon-plugins, pull requests merged in 2022-01, with the labels that each got.

#3363 (plugin): hardware::devices::hikvision::nvr::snmp
  hardware/devices/hikvision/nvr/snmp/mode/disks.pm
  hardware/devices/hikvision/nvr/snmp/mode/memory.pm
  hardware/devices/hikvision/nvr/snmp/mode/uptime.pm
  hardware/devices/hikvision/nvr/snmp/plugin.pm
Labels: new

#3365 (plugin): apps::virtualization::hpe::simplivity::restapi
  apps/virtualization/hpe/simplivity/restapi/custom/api.pm
  apps/virtualization/hpe/simplivity/restapi/mode/discovery.pm
  apps/virtualization/hpe/simplivity/restapi/mode/hosts.pm
  apps/virtualization/hpe/simplivity/restapi/mode/listhosts.pm
  apps/virtualization/hpe/simplivity/restapi/mode/omnistackclusters.pm
  apps/virtualization/hpe/simplivity/restapi/mode/virtualmachines.pm
  apps/virtualization/hpe/simplivity/restapi/plugin.pm
  network/microsens/g6/snmp/mode/sfp.pm
Labels: new

#3367 (plugin): fortinet fortiswitch snmp
  network/fortinet/fortiswitch/snmp/mode/cpu.pm
  network/fortinet/fortiswitch/snmp/mode/disk.pm
  network/fortinet/fortiswitch/snmp/mode/interfaces.pm
  network/fortinet/fortiswitch/snmp/mode/memory.pm
  network/fortinet/fortiswitch/snmp/mode/uptime.pm
  network/fortinet/fortiswitch/snmp/plugin.pm
Labels: new

#3369 (plugin): network::barracuda::bma::snmp::plugin
  network/barracuda/bma/snmp/mode/load.pm
  network/barracuda/bma/snmp/mode/mails.pm
  network/barracuda/bma/snmp/mode/storage.pm
  network/barracuda/bma/snmp/plugin.pm
Labels: new

#3370 (plugins/lib): output - remove pipe character if no perfdatas
  centreon/plugins/output.pm
Labels: enhancement

#3373 (plugin): network::lenovo::rackswitch::snmp::plugin
  network/lenovo/rackswitch/snmp/mode/cpu.pm
  network/lenovo/rackswitch/snmp/mode/hardware.pm
  network/lenovo/rackswitch/snmp/mode/interfaces.pm
  network/lenovo/rackswitch/snmp/mode/memory.pm
  network/lenovo/rackswitch/snmp/mode/resources.pm
  network/lenovo/rackswitch/snmp/mode/uptime.pm
  network/lenovo/rackswitch/snmp/plugin.pm
Labels: new

#3374 (plugin) storage::synology::snmp - add disk bad sectors
  storage/synology/snmp/mode/components/disk.pm
  storage/synology/snmp/mode/hardware.pm
Labels: enhancement

#3379 (plugin) cloud::azure::compute::disk - fixing missing unit causing error in output
  cloud/azure/compute/disk/mode/diskio.pm
Labels: enhancement

#3378 (plugin) cloud::azure::sqldatabase/sqlserver - refactoring, discovery, new modes
  cloud/azure/database/sqldatabase/mode/appresources.pm
  cloud/azure/database/sqldatabase/mode/connections.pm
  cloud/azure/database/sqldatabase/mode/databasesize.pm
  cloud/azure/database/sqldatabase/mode/databasestatus.pm
  cloud/azure/database/sqldatabase/mode/deadlocks.pm
  cloud/azure/database/sqldatabase/mode/discovery.pm
  cloud/azure/database/sqldatabase/mode/health.pm
  cloud/azure/database/sqldatabase/mode/sessions.pm
  cloud/azure/database/sqldatabase/mode/storage.pm
  cloud/azure/database/sqldatabase/mode/workers.pm
  cloud/azure/database/sqldatabase/plugin.pm
  cloud/azure/database/sqlserver/mode/health.pm
  cloud/azure/database/sqlserver/mode/serverstatus.pm
  cloud/azure/database/sqlserver/plugin.pm
Labels: enhancement, breaking change

#3381 (plugin): cloud::azure::compute::vmscalesets
  cloud/azure/compute/vmscalesets/mode/cpu.pm
  cloud/azure/compute/vmscalesets/mode/discovery.pm
  cloud/azure/compute/vmscalesets/mode/diskio.pm
  cloud/azure/compute/vmscalesets/mode/health.pm
  cloud/azure/compute/vmscalesets/mode/memory.pm
  cloud/azure/compute/vmscalesets/mode/traffic.pm
  cloud/azure/compute/vmscalesets/plugin.pm
Labels: new

#3386 (plugin) network::fortinet::fortigate::snmp - cluster-status add cpu and memory metrics
  centreon/common/fortinet/fortigate/snmp/mode/clusterstatus.pm
Labels: enhancement

#3390 (plugin) cloud::microsoft::office365::sharepoint - add --use-pseudonymize option for mode site-usage
  cloud/microsoft/office365/sharepoint/mode/listsites.pm
  cloud/microsoft/office365/sharepoint/mode/siteusage.pm
Labels: enhancement

#3391 (plugin) cloud::azure::database::sqlserver - rollback server-status & update to threshold_ng
  cloud/azure/database/sqlserver/mode/discovery.pm
  cloud/azure/database/sqlserver/mode/health.pm
  cloud/azure/database/sqlserver/mode/serverstatus.pm
  cloud/azure/database/sqlserver/plugin.pm
Labels: fix

#3393 (plugin) network::alcatel::omniswitch::snmp - mode hardware change default threshold for…
  network/alcatel/omniswitch/snmp/mode/components/backplane.pm
  network/alcatel/omniswitch/snmp/mode/components/chassis.pm
  network/alcatel/omniswitch/snmp/mode/components/container.pm
  network/alcatel/omniswitch/snmp/mode/components/fan.pm
  network/alcatel/omniswitch/snmp/mode/components/module.pm
  network/alcatel/omniswitch/snmp/mode/components/other.pm
  network/alcatel/omniswitch/snmp/mode/components/port.pm
  network/alcatel/omniswitch/snmp/mode/components/psu.pm
  network/alcatel/omniswitch/snmp/mode/components/resources.pm
  network/alcatel/omniswitch/snmp/mode/components/sensor.pm
  network/alcatel/omniswitch/snmp/mode/components/stack.pm
  network/alcatel/omniswitch/snmp/mode/components/unknown.pm
  network/alcatel/omniswitch/snmp/mode/hardware.pm
  network/alcatel/omniswitch/snmp/plugin.pm
Labels: enhancement

#3394 (plugin) apps::monitoring::netdata::restapi - mode get-chart wrong values
  apps/monitoring/netdata/restapi/mode/getchart.pm
Labels: bug

#3397 (plugin) cloud::azure::management::recovery - backupitemstatus - allow global perfdata
  cloud/azure/management/recovery/mode/backupitemsstatus.pm
Labels: enhancement

#3398 (plugins/lib) mode interfaces add option --check-metrics
  centreon/common/cisco/standard/snmp/mode/interfaces.pm
  centreon/common/fortinet/fortigate/snmp/mode/interfaces.pm
  network/adva/fsp3000/snmp/mode/interfaces.pm
  network/atrica/snmp/mode/connections.pm
  network/brocade/snmp/mode/interfaces.pm
  network/dlink/standard/snmp/mode/interfaces.pm
  network/extreme/snmp/mode/interfaces.pm
  network/fortinet/fortiswitch/snmp/mode/interfaces.pm
  network/hp/procurve/snmp/mode/interfaces.pm
  network/juniper/common/junos/mode/interfaces.pm
  network/lenovo/rackswitch/snmp/mode/interfaces.pm
  network/microsens/g6/snmp/mode/interfaces.pm
  network/mikrotik/snmp/mode/interfaces.pm
  network/mrv/optiswitch/snmp/mode/interfaces.pm
  snmp_standard/mode/interfaces.pm
  storage/lenovo/iomega/snmp/mode/interfaces.pm
Labels: enhancement

#3399 (plugin) hardware::devices::hikvision::nvr::isapi
  centreon/plugins/backend/http/curl.pm
  centreon/plugins/backend/http/lwp.pm
  hardware/devices/hikvision/nvr/isapi/custom/api.pm
  hardware/devices/hikvision/nvr/isapi/mode/cpu.pm
  hardware/devices/hikvision/nvr/isapi/mode/device.pm
  hardware/devices/hikvision/nvr/isapi/mode/disks.pm
  hardware/devices/hikvision/nvr/isapi/mode/memory.pm
  hardware/devices/hikvision/nvr/isapi/mode/protocols.pm
  hardware/devices/hikvision/nvr/isapi/mode/time.pm
  hardware/devices/hikvision/nvr/isapi/mode/uptime.pm
  hardware/devices/hikvision/nvr/isapi/plugin.pm
Labels: new

#3402 (plugin) database::mssql - mode backup-age uninitialized value
  database/mssql/mode/backupage.pm
Labels: bug

#3406 (plugin) apps::protocols::http - add collection mode
  apps/protocols/http/mode/collection.pm
  apps/protocols/http/plugin.pm
Labels: new

#3407 (plugin) apps::virtualization::hpe::simplivity::restapi - authentication
  apps/virtualization/hpe/simplivity/restapi/custom/api.pm
  apps/virtualization/hpe/simplivity/restapi/mode/virtualmachines.pm
Labels: fix

#3413 (plugin) apps::monitoring::iplabel::ekara::restapi - new
  apps/monitoring/iplabel/ekara/restapi/custom/api.pm
  apps/monitoring/iplabel/ekara/restapi/mode/discovery.pm
  apps/monitoring/iplabel/ekara/restapi/mode/incidents.pm
  apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
  apps/monitoring/iplabel/ekara/restapi/plugin.pm
Labels: plugin, new

#3418 add(watchguard): mode cluster
  network/watchguard/snmp/mode/cluster.pm
  network/watchguard/snmp/plugin.pm
Labels: enhancement, mode

#3422 (plugin) cloud::microsoft::office365::management - add mode app-credentials
  centreon/plugins/misc.pm
  cloud/microsoft/office365/custom/graphapi.pm
  cloud/microsoft/office365/management/mode/appcredentials.pm
  cloud/microsoft/office365/management/plugin.pm
Labels: mode

#3425 (plugin) network::fortinet::fortiadc::snmp
  network/fortinet/fortiadc/snmp/mode/components/fan.pm
  network/fortinet/fortiadc/snmp/mode/components/temperature.pm
  network/fortinet/fortiadc/snmp/mode/cpu.pm
  network/fortinet/fortiadc/snmp/mode/hardware.pm
  network/fortinet/fortiadc/snmp/mode/interfaces.pm
  network/fortinet/fortiadc/snmp/mode/listvirtualservers.pm
  network/fortinet/fortiadc/snmp/mode/memory.pm
  network/fortinet/fortiadc/snmp/mode/security.pm
  network/fortinet/fortiadc/snmp/mode/uptime.pm
  network/fortinet/fortiadc/snmp/mode/virtualservers.pm
  network/fortinet/fortiadc/snmp/plugin.pm
  storage/netapp/ontap/snmp/mode/plexes.pm
Labels: new

#3426 (plugin) apps::microsoft::activedirectory::wsman - refactoring dcdiag mode
  apps/microsoft/activedirectory/wsman/mode/dcdiag.pm
Labels: enhancement

#3427 (plugin) network::h3c::snmp - mode hardware snmp management
  centreon/common/h3c/snmp/mode/hardware.pm
Labels: enhancement

#3429 (plugin) database::mssql - mode backup-age thresholds issue
  database/mssql/mode/backupage.pm
Labels: fix

#3433 (plugin) database::oracle - refactoring rman-backup-problems mode
  database/oracle/mode/rmanbackupproblems.pm
Labels: breaking change

#3439 (plugin) hardware::server::dell::idrac::snmp - add hardware heath nam…
  hardware/server/dell/idrac/snmp/mode/components/health.pm
Labels: enhancement

#3441 (plugin) database::postgres - query-time mode filtering option
  database/postgres/mode/querytime.pm
Labels: bug

#3445 (plugin) apps::vtom::restapi - add legacy api
  apps/vtom/restapi/custom/legacy.pm
  apps/vtom/restapi/mode/jobs.pm
  apps/vtom/restapi/plugin.pm
Labels: enhancement
