Repository centreon/centreon-plugins, pull requests merged in 2022-08, with the labels that each got.

#3791 cloud::microsoft::office365::azuread - add Directory Size usage check (AD Quota)
  cloud/microsoft/office365/azuread/mode/directorysizeusage.pm
  cloud/microsoft/office365/azuread/plugin.pm
  cloud/microsoft/office365/custom/graphapi.pm
Labels: new

#3795 snmp_standard::mode::storage - empty --filter-storage-type option
  snmp_standard/mode/storage.pm
Labels: enhancement

#3796 (plugin) storage::dell::powerstore::restapi - manage update DSA-2022-159
  storage/dell/powerstore/restapi/mode/alerts.pm
Labels: enhancement

#3797 (plugin) hardware::server::dell::vxm::restapi - new
  hardware/server/dell/vxm/restapi/custom/api.pm
  hardware/server/dell/vxm/restapi/mode/chassis.pm
  hardware/server/dell/vxm/restapi/mode/discovery.pm
  hardware/server/dell/vxm/restapi/mode/hosts.pm
  hardware/server/dell/vxm/restapi/plugin.pm
Labels: new

#3800 (plugin) cloud::prometheus::plugin - adding discovery mode
  cloud/prometheus/restapi/mode/discovery.pm
Labels: enhancement

#3801 (plugin) hardware::server::dell::vxm::restapi - add default curl backend
  hardware/server/dell/vxm/restapi/custom/api.pm
Labels: enhancement

#3799 (plugin) apps::monitoring::nodeexporter::windows - adding windows node exporter plugin
  apps/monitoring/nodeexporter/windows/mode/cpu.pm
  apps/monitoring/nodeexporter/windows/mode/listinterfaces.pm
  apps/monitoring/nodeexporter/windows/mode/liststorages.pm
  apps/monitoring/nodeexporter/windows/mode/memory.pm
  apps/monitoring/nodeexporter/windows/mode/services.pm
  apps/monitoring/nodeexporter/windows/mode/storage.pm
  apps/monitoring/nodeexporter/windows/mode/traffic.pm
  apps/monitoring/nodeexporter/windows/plugin.pm
Labels: new

#3803 (plugin) apps::monitoring::nodeexporter::linux - enhancements on options
  apps/monitoring/nodeexporter/linux/mode/cpu.pm
  apps/monitoring/nodeexporter/linux/mode/load.pm
  apps/monitoring/nodeexporter/linux/mode/memory.pm
  apps/monitoring/nodeexporter/linux/mode/storage.pm
  apps/monitoring/nodeexporter/linux/mode/traffic.pm
Labels: enhancement

#3810 (plugin) storage::dell::me4::restapi - fix service discovery modes and fix help
  storage/dell/me4/restapi/mode/controllerstatistics.pm
  storage/dell/me4/restapi/mode/listcontrollers.pm
  storage/dell/me4/restapi/mode/listvolumes.pm
  storage/dell/me4/restapi/mode/volumestatistics.pm
Labels: bug

#3812 (plugin) storage::dell::me4::restapi - fix help
  storage/dell/me4/restapi/mode/controllerstatistics.pm
  storage/dell/me4/restapi/mode/volumestatistics.pm
Labels: bugfix

#3811 (plugin) cloud::azure::management::recovery - adding filter on timeframe for backup job status
  cloud/azure/custom/api.pm
  cloud/azure/management/recovery/mode/backupjobsstatus.pm
Labels: enhancement

#3815 (plugin) apps::monitoring::nodeexporter - fixing storage output and remove default filter
  apps/monitoring/nodeexporter/linux/mode/storage.pm
  apps/monitoring/nodeexporter/windows/mode/storage.pm
Labels: bugfix

#3804 (plugin) cloud::azure::* Migrate from the legacy codebase to the new one
  cloud/azure/compute/virtualmachine/mode/cpu.pm
  cloud/azure/compute/virtualmachine/mode/diskio.pm
  cloud/azure/compute/virtualmachine/mode/memory.pm
  cloud/azure/compute/virtualmachine/mode/network.pm
  cloud/azure/compute/virtualmachine/mode/vmsstate.pm
  cloud/azure/custom/mode.pm
  cloud/azure/network/expressroute/mode/circuitstatus.pm
  cloud/azure/network/expressroute/mode/traffic.pm
  cloud/azure/network/vpngateway/mode/sitetraffic.pm
  cloud/azure/network/vpngateway/mode/tunneltraffic.pm
  cloud/azure/network/vpngateway/mode/vpngatewaystatus.pm
Labels: enhancement, breaking change

#3816 (plugin) apps::protocols::http - mode collection add authentication system
  apps/protocols/http/mode/collection.pm
Labels: enhancement

#3817 (plugin) network::cisco::standard::snmp - add mode bgp
  centreon/common/cisco/standard/snmp/mode/bgp.pm
  network/cisco/standard/snmp/plugin.pm
Labels: enhancement

#3818 Fix missing condition in AWS Unified disco
  cloud/aws/cloudwatch/mode/discovery.pm
  cloud/aws/custom/awscli.pm
Labels: enhancement

#3819 network::netgear::sseries::snmp - perfdata v2 for interfaces mode
  network/netgear/sseries/snmp/mode/interfaces.pm
  network/netgear/sseries/snmp/plugin.pm
Labels: enhancement

#3821 network::brocade::snmp - add fcPortName for list-interfaces mode
  network/brocade/snmp/mode/listinterfaces.pm
  network/brocade/snmp/plugin.pm
Labels: enhancement

#3823 os::linux::local - mode traffic fix regexp
  os/linux/local/mode/traffic.pm
Labels: bugfix

#3826 (plugin) cloud::azure::management::recovery - modify counter type
  cloud/azure/management/recovery/mode/backupjobsstatus.pm
Labels: bugfix

#3836 (plugin) network::cisco::umbrella - Fix regex in appliance.pm mode
  network/cisco/umbrella/snmp/mode/appliance.pm
Labels: bugfix

#3806 (plugin) storage::dell::powerstore::restapi - add clusters mode
  storage/dell/powerstore/restapi/custom/api.pm
  storage/dell/powerstore/restapi/mode/clusters.pm
  storage/dell/powerstore/restapi/plugin.pm
  storage/hp/storeonce/4/restapi/mode/stores.pm
Labels: enhancement

#3838 (plugin) storage::dell::powerstore::restapi - use milliseconds for mo…
  storage/dell/powerstore/restapi/mode/clusters.pm
Labels: enhancement

#3839 (plugin) apps::backup::netbackup::local - mode jobs add filter options
  apps/backup/netbackup/local/mode/jobstatus.pm
Labels: enhancement

#3841 (plugin) network::cisco::standard::snmp - add metrics for bgp mode
  centreon/common/cisco/standard/snmp/mode/bgp.pm
Labels: enhancement

#3842 (plugin) apps::protocols::http - collection mode exit issue
  apps/protocols/http/mode/collection.pm
Labels: bug

#3843 (plugin) database::oracle::plugin - mode fra-usage add global metrics
  database/oracle/mode/frausage.pm
Labels: enhancement, breaking change

#3844 (plugin) storage::synology::snmp - add components disk health
  storage/synology/snmp/mode/components/disk.pm
  storage/synology/snmp/mode/hardware.pm
Labels: enhancement

#3845 (plugin) os::linux::local - add snmp discovery extra-oids option
  os/linux/local/mode/discoverysnmp.pm
  os/linux/local/mode/discoverysnmpv3.pm
Labels: enhancement

#3846 (plugin) network::aruba::aoscx::snmp - add cpu and memory modes
  network/aruba/aoscx/snmp/mode/cpu.pm
  network/aruba/aoscx/snmp/mode/memory.pm
  network/aruba/aoscx/snmp/plugin.pm
Labels: enhancement

#3847 (plugin) cloud::azure::compute::virtualmachine - remove vm-state mode, add API version for each mode
  cloud/azure/compute/virtualmachine/mode/cpu.pm
  cloud/azure/compute/virtualmachine/mode/diskio.pm
  cloud/azure/compute/virtualmachine/mode/listresources.pm
  cloud/azure/compute/virtualmachine/mode/memory.pm
  cloud/azure/compute/virtualmachine/mode/network.pm
  cloud/azure/compute/virtualmachine/mode/vmsizes.pm
  cloud/azure/compute/virtualmachine/mode/vmsstate.pm
  cloud/azure/compute/virtualmachine/plugin.pm
  cloud/azure/management/monitor/mode/discovery.pm
  cloud/azure/management/monitor/mode/health.pm
Labels: bugfix

#3848 (plugin) apps::vmware::vcsa::restapi - add new authenticate endpoint
  apps/vmware/vcsa/restapi/custom/api.pm
Labels: enhancement

#3849 (plugin) network::hp::moonshot::snmp - interfaces metric v2
  network/hp/moonshot/snmp/mode/interfaces.pm
  network/hp/moonshot/snmp/plugin.pm
Labels: enhancement

#3850 (plugin) apps::microsoft::sccm::local::mode::databasereplicationstatus - fix unknown thresholds error
  apps/microsoft/sccm/local/mode/databasereplicationstatus.pm
Labels: bugfix

#3853 (core) add ssl option eval system
  apps/protocols/x509/custom/tcp.pm
  centreon/plugins/misc.pm
  centreon/plugins/nrpe.pm
  database/mongodb/custom/driver.pm
Labels: enhancement

#3855 (plugin) storage::dell::powerstore::restapi - mode clusters milliseco…
  storage/dell/powerstore/restapi/mode/clusters.pm
Labels: bugfix

#3859 (plugin) cloud::azure::custom::azcli - adding missing function to azcli custom mode
  cloud/azure/custom/azcli.pm
Labels: bugfix

#3858 (plugin) cloud::azure::management::recovery - adding mode to monitor Azure replication health
  cloud/azure/custom/api.pm
  cloud/azure/custom/azcli.pm
  cloud/azure/management/recovery/mode/listreplicateditems.pm
  cloud/azure/management/recovery/mode/replicationhealth.pm
  cloud/azure/management/recovery/plugin.pm
Labels: enhancement

#3860 (plugin) apps::backup::veeam::local - add exclude filters + scheduled…
  apps/backup/veeam/local/mode/jobstatus.pm
  apps/backup/veeam/local/mode/repositories.pm
  apps/backup/veeam/local/mode/tapejobs.pm
  apps/backup/veeam/local/mode/vsbjobs.pm
  centreon/common/powershell/veeam/jobstatus.pm
Labels: enhancement

#3863 (plugin) notification::microsoft::office365::teams::plugin - adding redirection to newer resource status pages
  notification/microsoft/office365/teams/mode/alert.pm
Labels: enhancement

#3867 (plugin) network::efficientip::snmp - adding status mode
  network/efficientip/snmp/mode/status.pm
  network/efficientip/snmp/plugin.pm
Labels: enhancement

#3868 (plugin) network::efficientip::snmp::mode::status - removing testing var
  network/efficientip/snmp/mode/status.pm
Labels: bugfix

#3862 (plugin) storage::hp::3par::ssh - add multiple modes
  storage/hp/3par/ssh/mode/afc.pm
  storage/hp/3par/ssh/mode/cages.pm
  storage/hp/3par/ssh/mode/capacity.pm
  storage/hp/3par/ssh/mode/components/battery.pm
  storage/hp/3par/ssh/mode/components/cim.pm
  storage/hp/3par/ssh/mode/components/disk.pm
  storage/hp/3par/ssh/mode/components/node.pm
  storage/hp/3par/ssh/mode/components/port.pm
  storage/hp/3par/ssh/mode/components/psu.pm
  storage/hp/3par/ssh/mode/components/sensor.pm
  storage/hp/3par/ssh/mode/components/wsapi.pm
  storage/hp/3par/ssh/mode/diskusage.pm
  storage/hp/3par/ssh/mode/hardware.pm
  storage/hp/3par/ssh/mode/nodes.pm
  storage/hp/3par/ssh/mode/psu.pm
  storage/hp/3par/ssh/mode/time.pm
  storage/hp/3par/ssh/mode/uptime.pm
  storage/hp/3par/ssh/mode/volumeusage.pm
  storage/hp/3par/ssh/plugin.pm
Labels: enhancement

#3870 (plugin) cloud::iics::restapi - new
  cloud/iics/restapi/custom/api.pm
  cloud/iics/restapi/mode/agents.pm
  cloud/iics/restapi/mode/listagents.pm
  cloud/iics/restapi/plugin.pm
Labels: new

#3871 (plugin) cloud::iics::restapi - reconnect
  cloud/iics/restapi/custom/api.pm
  storage/hp/storeonce/4/restapi/custom/api.pm
Labels: enhancement

#3873 (plugin) storage::hp::3par::ssh - fix new modes
  storage/hp/3par/ssh/mode/afc.pm
  storage/hp/3par/ssh/mode/cages.pm
  storage/hp/3par/ssh/mode/capacity.pm
  storage/hp/3par/ssh/mode/nodes.pm
  storage/hp/3par/ssh/mode/psu.pm
  storage/hp/3par/ssh/mode/time.pm
  storage/hp/3par/ssh/mode/uptime.pm
Labels: enhancement
