Repository centreon/centreon-plugins, pull requests merged in 2022-02, with the labels that each got.

#3449 (plugin) apps::backup::veeam::local - thresholds of vsb-jobs
  apps/backup/veeam/local/mode/vsbjobs.pm
Labels: enhancement

#3450 (plugin) apps::protocols::http - add payload options for collection
  apps/protocols/http/mode/collection.pm
Labels: enhancement

#3451 (plugin) os::windows::wsman
  os/windows/wsman/mode/cpu.pm
  os/windows/wsman/mode/filesdate.pm
  os/windows/wsman/mode/filessize.pm
  os/windows/wsman/mode/interfaces.pm
  os/windows/wsman/mode/listinterfaces.pm
  os/windows/wsman/mode/listprocesses.pm
  os/windows/wsman/mode/listservices.pm
  os/windows/wsman/mode/liststorages.pm
  os/windows/wsman/mode/memory.pm
  os/windows/wsman/mode/pages.pm
  os/windows/wsman/mode/processes.pm
  os/windows/wsman/mode/services.pm
  os/windows/wsman/mode/storages.pm
  os/windows/wsman/mode/time.pm
  os/windows/wsman/mode/uptime.pm
  os/windows/wsman/plugin.pm
Labels: new

#3455 (plugin) cloud::azure::database::mysql::plugin - Add info about the resource type in help
  cloud/azure/database/mysql/mode/queries.pm
Labels: enhancement

#3456 (plugin) os::windows::wsman - add pending-reboot
  centreon/plugins/wsman.pm
  os/windows/wsman/mode/pendingreboot.pm
  os/windows/wsman/plugin.pm
Labels: enhancement

#3462 (plugin) database::oracle - add timeout option for sqlpluscmd
  database/oracle/sqlpluscmd.pm
Labels: enhancement

#3464 (plugin) apps::centreon::local - convert queue_file_enabled to yes/no
  apps/centreon/local/mode/brokerstats.pm
Labels: fix

#3466 (plugin) network::cisco::meraki::cloudcontroller::restapi - change cache system + add pagination
  network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/apirequests.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/cache.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/discovery.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/listdevices.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/listtags.pm
  network/cisco/meraki/cloudcontroller/restapi/mode/networks.pm
  network/cisco/meraki/cloudcontroller/restapi/plugin.pm
Labels: breaking change

#3468 (plugin) http curl backend - digest option regression
  centreon/plugins/backend/http/curl.pm
Labels: bug

#3470 (plugin) os::linux::local - ntp mode can check both ntp mode
  os/linux/local/mode/ntp.pm
Labels: enhancement

#3471 (plugin) network::viptela::snmp
  network/viptela/snmp/mode/components/fan.pm
  network/viptela/snmp/mode/components/led.pm
  network/viptela/snmp/mode/components/nim.pm
  network/viptela/snmp/mode/components/pem.pm
  network/viptela/snmp/mode/components/pim.pm
  network/viptela/snmp/mode/components/temperature.pm
  network/viptela/snmp/mode/components/usb.pm
  network/viptela/snmp/mode/controlconnections.pm
  network/viptela/snmp/mode/cpu.pm
  network/viptela/snmp/mode/disk.pm
  network/viptela/snmp/mode/gretunnels.pm
  network/viptela/snmp/mode/hardware.pm
  network/viptela/snmp/mode/interfaces.pm
  network/viptela/snmp/mode/listgretunnels.pm
  network/viptela/snmp/mode/memory.pm
  network/viptela/snmp/mode/uptime.pm
  network/viptela/snmp/plugin.pm
Labels: new

#3472 (plugin) network::viptela::snmp - clean memory mode
  network/viptela/snmp/mode/memory.pm
Labels: enhancement

#3473 (plugin) network::hp::procurve::snmp - mode virtual-chassis add --fil…
  network/hp/procurve/snmp/mode/virtualchassis.pm
Labels: enhancement

#3474 (plugin) os::windows::wsman - minor fixes
  os/windows/wsman/mode/filessize.pm
  os/windows/wsman/mode/interfaces.pm
Labels: bug

#3480 (plugin) database::mysql - add nlabel to mysql modes
  database/mysql/mode/innodbbufferpoolhitrate.pm
  database/mysql/mode/longqueries.pm
  database/mysql/mode/myisamkeycachehitrate.pm
  database/mysql/mode/openfiles.pm
  database/mysql/mode/opentables.pm
  database/mysql/mode/qcachehitrate.pm
  database/mysql/mode/slowqueries.pm
  database/mysql/mode/tablescount.pm
  database/mysql/mode/uptime.pm
Labels: enhancement, breaking change

#3488 (plugin) database::mssql - mode backup-age add option --full-as-incre…
  database/mssql/mode/backupage.pm
Labels: enhancement

#3490 (plugin) apps::protocol::http - mode collection add constants for htt…
  apps/protocols/http/mode/collection.pm
Labels: enhancement

#3500 (plugin) cloud::ibm::softlayer - fix help
  cloud/ibm/softlayer/mode/events.pm
  cloud/ibm/softlayer/mode/opentickets.pm
Labels: enhancement

#3503 (plugin) apps::monitoring::netdata::restapi - mode disks use family for fs-name
  apps/monitoring/netdata/restapi/mode/disks.pm
  apps/monitoring/netdata/restapi/mode/listdisks.pm
Labels: enhancement

#3505 (plugin) apps::monitoring::netdata::restapi - help get-charts
  apps/monitoring/netdata/restapi/mode/getchart.pm
Labels: enhancement

#3506 (core) snmp_standard::mode::interfaces - fix percentage display outpu…
  os/windows/wsman/mode/interfaces.pm
  snmp_standard/mode/interfaces.pm
Labels: bug
