Repository centreon/centreon-plugins, pull requests merged in 2022-10, with the labels that each got.

#3951 (plugin) os::aix::local - mode errpt fix empty options
  os/aix/local/mode/errpt.pm
Labels: bugfix

#3950 (plugin) os::aix::local - mode lvsync fix --filter-mount option
  os/aix/local/mode/lvsync.pm
Labels: bugfix

#3955 (plugin) storage::hp::3par::ssh - some minor fixes
  storage/hp/3par/ssh/mode/cages.pm
  storage/hp/3par/ssh/mode/time.pm
Labels: bugfix

#3954 (plugin) network::f5::bigip::snmp - mode pool-status add members information
  network/f5/bigip/snmp/mode/poolstatus.pm
Labels: enhancement

#3953 (plugin) cloud::microsoft::office365::...::servicestatus - Enhance Office 365 service status service by including the alert classification
  cloud/microsoft/office365/management/mode/servicestatus.pm
Labels: enhancement

#3959 (plugin) storage::hp::p2000::xmlapi - mode time use good timezone
  storage/hp/p2000/xmlapi/mode/time.pm
Labels: enhancement

#3956 (plugin) network::f5::bigip::snmp - mode pool-status add disabledbypa…
  network/f5/bigip/snmp/mode/poolstatus.pm
Labels: enhancement

#3962 (plugin) hardware::ups::powerware::snmp - mode input-lines fix wrong …
  hardware/ups/powerware/snmp/mode/batterystatus.pm
  hardware/ups/powerware/snmp/mode/inputlines.pm
  hardware/ups/powerware/snmp/mode/outputlines.pm
Labels: bugfix

#3963 (plugin) apps::vmware::vcsa::snmp - new
  apps/vmware/vcsa/snmp/mode/cpu.pm
  apps/vmware/vcsa/snmp/mode/interfaces.pm
  apps/vmware/vcsa/snmp/mode/listinterfaces.pm
  apps/vmware/vcsa/snmp/mode/memory.pm
  apps/vmware/vcsa/snmp/mode/storage.pm
  apps/vmware/vcsa/snmp/mode/uptime.pm
  apps/vmware/vcsa/snmp/plugin.pm
Labels: new

#3927 (plugin) apps::monitoring::splunk - adding plugin to monitor Splunk
  apps/monitoring/splunk/custom/api.pm
  apps/monitoring/splunk/mode/indexupdate.pm
  apps/monitoring/splunk/mode/query.pm
  apps/monitoring/splunk/mode/splunkdhealth.pm
  apps/monitoring/splunk/plugin.pm
Labels: new

#3965 (plugin) database::oracle - mode asm-diskgroup-usage fix errors
  database/oracle/mode/asmdiskgroupusage.pm
Labels: bugfix

#3968 (plugin) storage::netapp::ontap::restapi - mode volumes fix latency m…
  storage/netapp/ontap/restapi/mode/volumes.pm
Labels: bugfix

#3967 (plugin) storage::fujitsu::eternus::dx::ssh - use ssh backends
  centreon/plugins/script_custom/cli.pm
  storage/fujitsu/eternus/dx/ssh/mode/cpu.pm
  storage/fujitsu/eternus/dx/ssh/mode/physicaldisk.pm
  storage/fujitsu/eternus/dx/ssh/mode/portstats.pm
  storage/fujitsu/eternus/dx/ssh/mode/psu.pm
  storage/fujitsu/eternus/dx/ssh/mode/raidgroups.pm
  storage/fujitsu/eternus/dx/ssh/mode/volumestats.pm
  storage/fujitsu/eternus/dx/ssh/plugin.pm
Labels: enhancement, bugfix

#3946 (plugin) apps::monitoring::kadiska - adding new metrics and filters
  apps/monitoring/kadiska/custom/api.pm
  apps/monitoring/kadiska/mode/listwatchers.pm
  apps/monitoring/kadiska/mode/watcherstatistics.pm
Labels: enhancement

#3977 (plugin) os::linux::local - mode connections fix netstat mode
  os/linux/local/mode/connections.pm
Labels: bugfix

#3982 (plugin) database::postgres - mode backends fix --noidle option
  database/postgres/mode/backends.pm
Labels: bugfix

#3983 (plugin) database::oracle - mode fra-usage fix float comma
  database/oracle/mode/frausage.pm
  database/oracle/mode/longqueries.pm
Labels: bugfix

#3984 (plugin) database::mssql - mode failed-jobs add option --add-duration-perfdata
  database/mssql/mode/failedjobs.pm
Labels: enhancement

#3985 (plugin) apps::ceph::restapi - authentication issue
  apps/ceph/restapi/custom/api.pm
Labels: bugfix

#3986 (plugin) apps::ceph::restapi - mode pools fix metrics
  apps/ceph/restapi/mode/pools.pm
Labels: bugfix

#3987 (plugin) os::aix::local - add option --ignore-exit-code
  os/aix/local/custom/cli.pm
  os/aix/local/mode/storage.pm
Labels: enhancement

#3991 (plugin) apps::microsoft::wsus::local - mode computers-status fix
  centreon/common/powershell/wsus/computersstatus.pm
Labels: bugfix

#3994 (plugin) storage::hp::3par - fix help
  storage/hp/3par/ssh/mode/afc.pm
  storage/hp/3par/ssh/mode/cages.pm
Labels: bugfix

#3995 (plugin) os::linux::local - mode diskio fix %util calc
  os/linux/local/mode/diskio.pm
Labels: bugfix

#4000 update changelog for release 20221017
  changelog
Labels: documentation

#3996 (plugin) network::fortinet::fortigate::snmp - mode hardware fix strin…
  centreon/common/fortinet/fortigate/snmp/mode/hardware.pm
Labels: bugfix

#4003 Fix option name in snmp interfaces plugin
  snmp_standard/mode/interfaces.pm
Labels: bugfix

#4007 (plugin) os::windows::wsman - mode time fix timezone option
  os/windows/wsman/mode/time.pm
Labels: bugfix

#4009 (plugin) cloud::azure::storageaccount - Change output for human friendly output
  cloud/azure/common/storageaccount/filesharequota.pm
Labels: enhancement

#4011 (plugin) apps::monitoring::splunk - Fixing blank output for splunkd health mode
  apps/monitoring/splunk/mode/splunkdhealth.pm
Labels: bugfix

#4006 (plugin) os::picos::snmp - Adding PICOS plugin
  os/picos/snmp/mode/components/fan.pm
  os/picos/snmp/mode/components/psu.pm
  os/picos/snmp/mode/cpu.pm
  os/picos/snmp/mode/hardware.pm
  os/picos/snmp/mode/interfaces.pm
  os/picos/snmp/mode/listinterfaces.pm
  os/picos/snmp/mode/memory.pm
  os/picos/snmp/mode/temperature.pm
  os/picos/snmp/plugin.pm
  storage/qnap/snmp/mode/components/psu.pm
Labels: new

#3997 [storage::huawei::oceanstor::snmp::plugin] add lun discover and check usage
  storage/huawei/oceanstor/snmp/mode/listluns.pm
  storage/huawei/oceanstor/snmp/mode/luns.pm
  storage/huawei/oceanstor/snmp/plugin.pm
Labels: enhancement

#4012 (plugin) storage::huawei::oceanstor - mode luns minor fixes
  storage/huawei/oceanstor/snmp/mode/listluns.pm
  storage/huawei/oceanstor/snmp/mode/luns.pm
Labels: bugfix

#4013 (plugin) apps::protocols::snmp - add discovery mode
  apps/protocols/snmp/plugin.pm
  snmp_standard/mode/discovery.pm
Labels: enhancement

#4024 (plugin) cloud::azure::management::cost - adding mode to query subscription costs
  cloud/azure/custom/api.pm
  cloud/azure/management/costs/mode/costsexplorer.pm
  cloud/azure/management/costs/plugin.pm
Labels: enhancement, new

#4019 (plugin) cloud::azure::management::costs - new modes to check azure config compliance
  cloud/azure/custom/api.pm
  cloud/azure/management/costs/mode/hybridbenefits.pm
  cloud/azure/management/costs/mode/orphanresources.pm
  cloud/azure/management/costs/mode/tagscompliance.pm
  cloud/azure/management/costs/plugin.pm
Labels: enhancement

#4023 (plugin) database::mssql::mode::* - Refactor some old-fashionned modes ...
  database/mssql/mode/cachehitratio.pm
  database/mssql/mode/connectedusers.pm
  database/mssql/mode/deadlocks.pm
  database/mssql/mode/lockswaits.pm
Labels: enhancement, breaking change
