Repository centreon/centreon-plugins, pull requests merged in 2023-06, with the labels that each got.

#4441 (plugin) network::cisco::standard::snmp - mode environment undefined …
  src/centreon/common/cisco/standard/snmp/mode/components/module.pm
Labels: bugfix

#4446 (plugin) hardware::sensors::apc::snmp - mode sensors undefined humidi…
  src/hardware/sensors/apc/snmp/mode/components/humidity.pm
Labels: bugfix

#4443 (plugin) apps::protocols::snmp - add snmp cache system
  src/apps/protocols/snmp/mode/cache.pm
  src/apps/protocols/snmp/plugin.pm
  src/centreon/plugins/snmp.pm
Labels: enhancement

#4447 (plugin) apps::wallix::bastion::snmp - mode license add --filter-cate…
  src/apps/wallix/bastion/snmp/mode/license.pm
Labels: enhancement

#4449 (plugin) cloud::aws::cloudtrail - new
  .github/workflows/tests-functional.yml
  packaging/centreon-plugin-Cloud-Aws-Cloudtrail-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Cloudtrail-Api/pkg.json
  packaging/centreon-plugin-Cloud-Aws-Cloudtrail-Api/rpm.json
  src/cloud/aws/cloudtrail/mode/checktrailstatus.pm
  src/cloud/aws/cloudtrail/mode/countevents.pm
  src/cloud/aws/cloudtrail/plugin.pm
  src/cloud/aws/custom/awscli.pm
  src/cloud/aws/custom/paws.pm
  tests/functional/cloud/aws/cloudtrail/checktrailstatus.sh
  tests/functional/cloud/aws/cloudtrail/countevents.sh
  tests/resources/mockoon/cloud-aws-cloudtrail.json
Labels: new

#4459 (plugin) apps::jenkins - mode jobs fix --filter-job-name option
  src/apps/jenkins/mode/jobs.pm
Labels: bugfix

#4463 (plugin) network/cisco/standard/snmp - mode interfaces add --add-qos-limit option
  src/centreon/common/cisco/standard/snmp/mode/interfaces.pm
Labels: enhancement

#4456 (plugin) apps::backup::veeam::vbem::restapi - new
  packaging/centreon-plugin-Applications-Veeam-Vbem-Restapi/deb.json
  packaging/centreon-plugin-Applications-Veeam-Vbem-Restapi/pkg.json
  packaging/centreon-plugin-Applications-Veeam-Vbem-Restapi/rpm.json
  src/apps/backup/veeam/vbem/restapi/custom/api.pm
  src/apps/backup/veeam/vbem/restapi/mode/cache.pm
  src/apps/backup/veeam/vbem/restapi/mode/jobs.pm
  src/apps/backup/veeam/vbem/restapi/mode/listjobs.pm
  src/apps/backup/veeam/vbem/restapi/mode/listrepositories.pm
  src/apps/backup/veeam/vbem/restapi/mode/repositories.pm
  src/apps/backup/veeam/vbem/restapi/plugin.pm
Labels: new

#4454 (plugin) database::mysql - force new perfdata
  src/centreon/common/protocols/sql/mode/connectiontime.pm
  src/database/mysql/mode/databasessize.pm
  src/database/mysql/mode/innodbbufferpoolhitrate.pm
  src/database/mysql/mode/longqueries.pm
  src/database/mysql/mode/myisamkeycachehitrate.pm
  src/database/mysql/mode/openfiles.pm
  src/database/mysql/mode/opentables.pm
  src/database/mysql/mode/passwordexpiration.pm
  src/database/mysql/mode/qcachehitrate.pm
  src/database/mysql/mode/queries.pm
  src/database/mysql/mode/slowqueries.pm
  src/database/mysql/mode/threadsconnected.pm
  src/database/mysql/mode/uptime.pm
  src/database/mysql/plugin.pm
Labels: enhancement

#4486 (plugin) network::cisco::meraki::cloudcontroller::restapi - add device.li…
  src/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/listdevices.pm
Labels: enhancement

#4479 (packaging) network::atrica::snmp - missing pm files
  packaging/centreon-plugin-Network-Routers-Atrica-Snmp/pkg.json
Labels: bugfix

#4476 (plugin) cloud::vmware::velocloud::restapi - fix empty return
  src/cloud/vmware/velocloud/restapi/mode/applicationusage.pm
  src/cloud/vmware/velocloud/restapi/mode/categoryusage.pm
  src/cloud/vmware/velocloud/restapi/mode/edgeqoe.pm
  src/cloud/vmware/velocloud/restapi/mode/edgestatus.pm
  src/cloud/vmware/velocloud/restapi/mode/linkstatus.pm
  src/cloud/vmware/velocloud/restapi/mode/linkusage.pm
Labels: bugfix

#4482 (plugin) apps::ipfabric - add list-paths mode and clean code
  src/apps/ipfabric/custom/api.pm
  src/apps/ipfabric/mode/discovery.pm
  src/apps/ipfabric/mode/listpaths.pm
  src/apps/ipfabric/mode/pathverification.pm
  src/apps/ipfabric/plugin.pm
Labels: enhancement

#4489 (plugin) cloud::prometheus::restapi - fix legacy compatibility
  src/cloud/prometheus/restapi/mode/expression.pm
Labels: bugfix

#4493 centreon::plugins::snmp - fix undefined value with discovery
  src/centreon/plugins/snmp.pm
Labels: bugfix

#4492 (plugin) network::oneaccess::snmp - mode cells-radio add option --cus…
  src/centreon/plugins/templates/counter.pm
  src/network/oneaccess/snmp/mode/cellsradio.pm
Labels: enhancement

#4495 (plugin) os::linux::local - fix improper AIX field descriptor
  src/os/linux/local/mode/process.pm
Labels: enhancement, bugfix

#4512 (core) clean copyright
  src/apps/backup/commvault/commserve/restapi/custom/api.pm
  src/apps/backup/commvault/commserve/restapi/plugin.pm
  src/apps/emc/ppma/restapi/custom/api.pm
  src/apps/emc/ppma/restapi/plugin.pm
  src/apps/proxmox/mg/restapi/custom/api.pm
  src/apps/proxmox/mg/restapi/plugin.pm
  src/apps/smartermail/restapi/custom/api.pm
  src/apps/smartermail/restapi/mode/licenses.pm
  src/apps/smartermail/restapi/mode/services.pm
  src/apps/smartermail/restapi/mode/spools.pm
  src/apps/smartermail/restapi/plugin.pm
  src/apps/virtualization/hpe/simplivity/restapi/custom/api.pm
  src/apps/virtualization/hpe/simplivity/restapi/mode/hosts.pm
  src/apps/virtualization/hpe/simplivity/restapi/mode/omnistackclusters.pm
  src/apps/virtualization/hpe/simplivity/restapi/mode/virtualmachines.pm
  src/apps/virtualization/hpe/simplivity/restapi/plugin.pm
  src/centreon/common/protocols/actuator/custom/centreonmap.pm
  src/network/aruba/aoscx/restapi/custom/api.pm
  src/network/aruba/aoscx/restapi/plugin.pm
  src/notification/centreon/opentickets/api/custom/api.pm
  src/notification/centreon/opentickets/api/mode/closehost.pm
  src/notification/centreon/opentickets/api/mode/closeservice.pm
  src/notification/centreon/opentickets/api/mode/openhost.pm
  src/notification/centreon/opentickets/api/mode/openservice.pm
  src/notification/centreon/opentickets/api/plugin.pm
  src/notification/microsoft/office365/teams/custom/webhookapi.pm
  src/storage/emc/vplex/restapi/custom/apiv2.pm
Labels: documentation

#4511 enh(plugin): add linux local list systemd services mode
  src/os/linux/local/mode/listsystemdservices.pm
  src/os/linux/local/plugin.pm
Labels: enhancement

#4510 (plugin) storage::dell::compellent::snmp - mode hardware add option -…
  src/storage/dell/compellent/snmp/mode/components/cache.pm
  src/storage/dell/compellent/snmp/mode/components/ctrl.pm
  src/storage/dell/compellent/snmp/mode/components/ctrlfan.pm
  src/storage/dell/compellent/snmp/mode/components/ctrlpower.pm
  src/storage/dell/compellent/snmp/mode/components/ctrltemp.pm
  src/storage/dell/compellent/snmp/mode/components/ctrlvoltage.pm
  src/storage/dell/compellent/snmp/mode/components/disk.pm
  src/storage/dell/compellent/snmp/mode/components/diskfolder.pm
  src/storage/dell/compellent/snmp/mode/components/encl.pm
  src/storage/dell/compellent/snmp/mode/components/enclfan.pm
  src/storage/dell/compellent/snmp/mode/components/encliomod.pm
  src/storage/dell/compellent/snmp/mode/components/enclpower.pm
  src/storage/dell/compellent/snmp/mode/components/encltemp.pm
  src/storage/dell/compellent/snmp/mode/components/resources.pm
  src/storage/dell/compellent/snmp/mode/components/sc.pm
  src/storage/dell/compellent/snmp/mode/components/server.pm
  src/storage/dell/compellent/snmp/mode/components/volume.pm
  src/storage/dell/compellent/snmp/mode/globalstatus.pm
  src/storage/dell/compellent/snmp/mode/hardware.pm
  src/storage/dell/compellent/snmp/plugin.pm
Labels: enhancement
