Repository centreon/centreon-plugins, pull requests merged in 2023-04, with the labels that each got.

#4328 (plugin) network::opengear::snmp - new
  packaging/centreon-plugin-Network-Opengear-Snmp/deb.json
  packaging/centreon-plugin-Network-Opengear-Snmp/pkg.json
  packaging/centreon-plugin-Network-Opengear-Snmp/rpm.json
  src/network/opengear/snmp/mode/cpudetailed.pm
  src/network/opengear/snmp/mode/interfaces.pm
  src/network/opengear/snmp/mode/listserialports.pm
  src/network/opengear/snmp/mode/load.pm
  src/network/opengear/snmp/mode/memory.pm
  src/network/opengear/snmp/mode/serialports.pm
  src/network/opengear/snmp/mode/uptime.pm
  src/network/opengear/snmp/plugin.pm
Labels: new

#4339 (plugin) storage::netapp::ontap::restapi - mode quotas change filters
  src/storage/netapp/ontap/restapi/mode/quotas.pm
Labels: enhancement

#4331 (plugin) apps::antivirus::clamav - mode update-status fix txt dns rec…
  src/apps/antivirus/clamav/local/mode/updatestatus.pm
Labels: bugfix

#4329 add password manager secret file
  src/centreon/plugins/passwordmgr/file.pm
Labels: enhancement

#4341 (plugin) storage::netapp::ontap::snmp - mode global-status harden cod…
  src/storage/netapp/ontap/snmp/mode/globalstatus.pm
Labels: bugfix

#4351 (plugin) apps::backup::commvault::commserve::restapi - mode jobs chan…
  src/apps/backup/commvault/commserve/restapi/custom/api.pm
  src/apps/backup/commvault/commserve/restapi/mode/jobs.pm
Labels: bugfix

#4360 (plugin) apps::controlm::restapi - mode jobs add option --display-ext…
  src/apps/controlm/restapi/mode/jobs.pm
Labels: enhancement

#4362 (plugin) apps::protocols::dns - option --nameservers can use coma
  src/apps/protocols/dns/lib/dns.pm
  src/apps/protocols/dns/mode/request.pm
Labels: enhancement

#4350 (plugin) cloud::outscale - new
  packaging/centreon-plugin-Cloud-Outscale-Api/deb.json
  packaging/centreon-plugin-Cloud-Outscale-Api/pkg.json
  packaging/centreon-plugin-Cloud-Outscale-Api/rpm.json
  src/cloud/outscale/custom/http.pm
  src/cloud/outscale/custom/osccli.pm
  src/cloud/outscale/mode/accountconsumptions.pm
  src/cloud/outscale/mode/clientgateways.pm
  src/cloud/outscale/mode/internetservices.pm
  src/cloud/outscale/mode/listclientgateways.pm
  src/cloud/outscale/mode/listinternetservices.pm
  src/cloud/outscale/mode/listloadbalancers.pm
  src/cloud/outscale/mode/listnatservices.pm
  src/cloud/outscale/mode/listnets.pm
  src/cloud/outscale/mode/listquotas.pm
  src/cloud/outscale/mode/listroutetables.pm
  src/cloud/outscale/mode/listsubnets.pm
  src/cloud/outscale/mode/listvirtualgateways.pm
  src/cloud/outscale/mode/listvms.pm
  src/cloud/outscale/mode/listvolumes.pm
  src/cloud/outscale/mode/listvpnconnections.pm
  src/cloud/outscale/mode/loadbalancers.pm
  src/cloud/outscale/mode/natservices.pm
  src/cloud/outscale/mode/nets.pm
  src/cloud/outscale/mode/quotas.pm
  src/cloud/outscale/mode/routetables.pm
  src/cloud/outscale/mode/subnets.pm
  src/cloud/outscale/mode/virtualgateways.pm
  src/cloud/outscale/mode/vms.pm
  src/cloud/outscale/mode/volumes.pm
  src/cloud/outscale/mode/vpnconnections.pm
  src/cloud/outscale/plugin.pm
Labels: new

#4364 (plugin) apps::protocols::x509 - add support for verify_hostname
  src/apps/protocols/x509/custom/tcp.pm
  src/apps/protocols/x509/mode/certificate.pm
Labels: enhancement

#4366 (plugin) cloud::azure::database::sqldatabase - fix --server option
  src/cloud/azure/database/sqldatabase/mode/connections.pm
  src/cloud/azure/database/sqldatabase/mode/deadlocks.pm
  src/cloud/azure/database/sqldatabase/mode/sessions.pm
  src/cloud/azure/database/sqldatabase/mode/storage.pm
  src/cloud/azure/database/sqldatabase/mode/workers.pm
  src/cloud/azure/database/sqldatabase/plugin.pm
Labels: bugfix

#4365 (plugin) cloud::azure::database::postgres - new
  packaging/centreon-plugin-Cloud-Azure-Database-Postgres-Api/deb.json
  packaging/centreon-plugin-Cloud-Azure-Database-Postgres-Api/pkg.json
  packaging/centreon-plugin-Cloud-Azure-Database-Postgres-Api/rpm.json
  src/cloud/azure/database/postgres/mode/connections.pm
  src/cloud/azure/database/postgres/mode/cpu.pm
  src/cloud/azure/database/postgres/mode/discovery.pm
  src/cloud/azure/database/postgres/mode/ioconsumption.pm
  src/cloud/azure/database/postgres/mode/memory.pm
  src/cloud/azure/database/postgres/mode/replication.pm
  src/cloud/azure/database/postgres/mode/storage.pm
  src/cloud/azure/database/postgres/mode/traffic.pm
  src/cloud/azure/database/postgres/plugin.pm
Labels: plugin, new

#4370 (plugin) network::sonus::sbc::snmp - refactoring + metric v2
  src/network/sonus/sbc/snmp/mode/callstats.pm
  src/network/sonus/sbc/snmp/mode/channels.pm
  src/network/sonus/sbc/snmp/mode/cpudetailed.pm
  src/network/sonus/sbc/snmp/mode/dspstats.pm
  src/network/sonus/sbc/snmp/mode/interfaces.pm
  src/network/sonus/sbc/snmp/mode/load.pm
  src/network/sonus/sbc/snmp/mode/memory.pm
  src/network/sonus/sbc/snmp/mode/storage.pm
  src/network/sonus/sbc/snmp/mode/swap.pm
  src/network/sonus/sbc/snmp/plugin.pm
Labels: enhancement, breaking change

#4373 (plugin) network::sonus::sbc::snmp - mode cpu metric v2
  src/network/sonus/sbc/snmp/mode/cpu.pm
  src/network/sonus/sbc/snmp/plugin.pm
Labels: enhancement

#4381 (plugin) network::barracuda::bma::snmp - mode mails fix help
  src/network/barracuda/bma/snmp/mode/mails.pm
Labels: bugfix

#4382 (plugin) cloud::aws::directconnect - new
  packaging/centreon-plugin-Cloud-Aws-Directconnect-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Directconnect-Api/pkg.json
  packaging/centreon-plugin-Cloud-Aws-Directconnect-Api/rpm.json
  src/cloud/aws/custom/awscli.pm
  src/cloud/aws/custom/mode.pm
  src/cloud/aws/custom/paws.pm
  src/cloud/aws/directconnect/mode/connections.pm
  src/cloud/aws/directconnect/mode/discovery.pm
  src/cloud/aws/directconnect/mode/listconnections.pm
  src/cloud/aws/directconnect/mode/listvirtualinterfaces.pm
  src/cloud/aws/directconnect/mode/virtualinterfaces.pm
  src/cloud/aws/directconnect/plugin.pm
Labels: plugin, new

#4352 (plugin) hardware::devices::hms::netbiter::argos::restapi - new
  packaging/centreon-plugin-Hardware-Devices-Hms-Netbiter-Argos-Restapi/deb.json
  packaging/centreon-plugin-Hardware-Devices-Hms-Netbiter-Argos-Restapi/pkg.json
  packaging/centreon-plugin-Hardware-Devices-Hms-Netbiter-Argos-Restapi/rpm.json
  src/hardware/devices/hms/netbiter/argos/restapi/custom/api.pm
  src/hardware/devices/hms/netbiter/argos/restapi/mode/alarms.pm
  src/hardware/devices/hms/netbiter/argos/restapi/mode/discovery.pm
  src/hardware/devices/hms/netbiter/argos/restapi/mode/listsensors.pm
  src/hardware/devices/hms/netbiter/argos/restapi/mode/sensors.pm
  src/hardware/devices/hms/netbiter/argos/restapi/plugin.pm
Labels: plugin, new

#4393 (plugin) network::stormshield::snmp - mode vpn-status fix threshold s…
  src/network/stormshield/snmp/mode/vpnstatus.pm
Labels: bugfix

#4391 (plugin) storage::ibm::storwize::ssh - mode hardware add option --add…
  src/centreon/plugins/templates/hardware.pm
  src/storage/ibm/storwize/ssh/mode/components/array.pm
  src/storage/ibm/storwize/ssh/mode/components/drive.pm
  src/storage/ibm/storwize/ssh/mode/components/enclosure.pm
  src/storage/ibm/storwize/ssh/mode/components/enclosurebattery.pm
  src/storage/ibm/storwize/ssh/mode/components/enclosurecanister.pm
  src/storage/ibm/storwize/ssh/mode/components/enclosurepsu.pm
  src/storage/ibm/storwize/ssh/mode/components/host.pm
  src/storage/ibm/storwize/ssh/mode/components/mdisk.pm
  src/storage/ibm/storwize/ssh/mode/components/node.pm
  src/storage/ibm/storwize/ssh/mode/components/portfc.pm
  src/storage/ibm/storwize/ssh/mode/components/portsas.pm
  src/storage/ibm/storwize/ssh/mode/components/quorum.pm
  src/storage/ibm/storwize/ssh/mode/components/systemstats.pm
  src/storage/ibm/storwize/ssh/mode/components/vdisk.pm
  src/storage/ibm/storwize/ssh/mode/hardware.pm
Labels: enhancement

#4368 (plugin) cloud::azure::database::sqldatabase - add modes cpu and memory
  src/cloud/azure/database/sqldatabase/mode/cpu.pm
  src/cloud/azure/database/sqldatabase/mode/memory.pm
  src/cloud/azure/database/sqldatabase/plugin.pm
Labels: enhancement

#4369 (plugin) cloud::azure::compute::aks - add modes memory, node-state, p…
  src/cloud/azure/compute/aks/mode/memory.pm
  src/cloud/azure/compute/aks/mode/nodestate.pm
  src/cloud/azure/compute/aks/mode/podstate.pm
  src/cloud/azure/compute/aks/mode/unschedulablepods.pm
  src/cloud/azure/compute/aks/plugin.pm
Labels: enhancement

#4387 (plugin) network::keysight::nvos::restapi - new
  packaging/centreon-plugin-Network-Keysight-Nvos-Restapi/deb.json
  packaging/centreon-plugin-Network-Keysight-Nvos-Restapi/pkg.json
  packaging/centreon-plugin-Network-Keysight-Nvos-Restapi/rpm.json
  src/network/keysight/nvos/restapi/custom/api.pm
  src/network/keysight/nvos/restapi/mode/dynamicfilters.pm
  src/network/keysight/nvos/restapi/mode/hardware.pm
  src/network/keysight/nvos/restapi/mode/listdynamicfilters.pm
  src/network/keysight/nvos/restapi/mode/listports.pm
  src/network/keysight/nvos/restapi/mode/ports.pm
  src/network/keysight/nvos/restapi/mode/time.pm
  src/network/keysight/nvos/restapi/mode/uptime.pm
  src/network/keysight/nvos/restapi/plugin.pm
Labels: plugin, new
