Repository centreon/centreon-plugins, pull requests merged in 2023-10, with the labels that each got.

#4535 (plugin) database::mongodb - add shards option
  src/database/mongodb/custom/driver.pm
  src/database/mongodb/mode/collectionstatistics.pm
  src/database/mongodb/mode/connections.pm
  src/database/mongodb/mode/connectiontime.pm
  src/database/mongodb/mode/databasestatistics.pm
  src/database/mongodb/mode/queries.pm
  src/database/mongodb/mode/replicationstatus.pm
  src/database/mongodb/plugin.pm
Labels: enhancement

#4642 (plugin) `network::aruba::aoscx::snmp` - mode hardware handle ready state
  src/network/aruba/aoscx/snmp/mode/hardware.pm
Labels: bugfix

#4664 (plugin) apps::monitoring::speedtest - add jitter unit
  src/apps/monitoring/speedtest/mode/internetbandwidth.pm
Labels: enhancement

#4668 (plugin) network::fortinet::fortigate::restapi - mode system fix not …
  src/network/fortinet/fortigate/restapi/mode/system.pm
Labels: bugfix

#4692 Change issue template
  .github/issue_template.md
Labels: documentation
