Repository centreon/centreon-plugins, pull requests merged in 2024-09, with the labels that each got.

#5148 CTOR-856 - HyperV2012 - Note-integration-service - Replace the default value of --filter-status
  src/apps/microsoft/hyperv/2012/local/mode/nodeintegrationservice.pm
  tests/apps/microsoft/hyperv/2012/local/nodeintegrationservice-2022-1.json
  tests/apps/microsoft/hyperv/2012/local/nodeintegrationservice-2022-2.json
  tests/apps/microsoft/hyperv/2012/local/nodeintegrationservice.robot
Labels: bugfix

#5170 fix(packaging): added missing Perl modules to all plugins
  .github/scripts/plugins-source.container.pl
  .github/workflows/plugins.yml
  src/centreon/plugins/output.pm
Labels: do-not-spellcheck

#5186 Quick fix on HPE-Primera-RestAPI
  src/storage/hp/primera/restapi/custom/api.pm
Labels: bugfix, internal

#5040 feat(dependencies) CTOR-596 - Add paws dependency to AWS plugins
  .github/packaging/centreon-plugin.yaml.template
  .github/scripts/test-all-plugins.py
  packaging/centreon-plugin-Cloud-Aws-Apigateway-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Apigateway-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Backup-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Backup-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Billing-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Billing-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Cloudfront-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Cloudfront-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Cloudtrail-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Cloudtrail-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Cloudwatch-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Cloudwatch-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Cloudwatchlogs-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Cloudwatchlogs-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Directconnect-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Directconnect-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Ebs-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Ebs-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Ec2-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Ec2-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Efs-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Efs-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Elasticache-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Elasticache-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Application-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Application-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Network-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Elb-Network-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Fsx-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Fsx-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Health-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Health-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Kinesis-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Kinesis-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Lambda-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Lambda-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Rds-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Rds-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-S3-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-S3-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Ses-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Ses-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Sns-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Sns-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Sqs-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Sqs-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Transitgateway-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Transitgateway-Api/rpm.json
  packaging/centreon-plugin-Cloud-Aws-Vpn-Api/deb.json
  packaging/centreon-plugin-Cloud-Aws-Vpn-Api/rpm.json
  tests/cloud/aws/cloudtrail/checktrailstatus.robot
  tests/cloud/aws/cloudtrail/cloud-aws-cloudtrail.json
  tests/cloud/aws/cloudtrail/countevents.robot
Labels: upload-artifacts, internal

#5208 new(lib): package new dependency coming from CPAN for AES
  .github/workflows/perl-cpan-libraries.yml
Labels: upload-artifacts

#5203 chore(packaging): update deb packages naming convention
  .github/actions/package-nfpm/action.yml
  .github/actions/parse-distrib/action.yml
  .github/actions/promote-to-stable/action.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-filesys-smbclient.yml
Labels: upload-artifacts

#5188 Plugin(network::stormshield::snmp) - Mode(Hardware) : Issue on temperature value not used
  src/network/stormshield/snmp/mode/components/temperature.pm
  tests/network/stormshield/snmp/hardware.robot
  tests/network/stormshield/snmp/stormshield-fake.snmpwalk
Labels: bugfix, internal

#5187 Fix power unit and add Voltage metric
  src/hardware/pdu/cyberpower/snmp/mode/load.pm
  tests/hardware/pdu/cyberpower/snmp/CyberPower.snmpwalk
  tests/hardware/pdu/cyberpower/snmp/load.robot
  tests/hardware/pdu/cyberpower/snmp/outlets.robot
Labels: enhancement, bugfix, internal

#5191 [Plugin(storage::wd::nas::snmp) - Modes(volumes, listvolumes, hardware) : add support for ex4100 model
  src/storage/wd/nas/snmp/mode/hardware.pm
  src/storage/wd/nas/snmp/mode/listvolumes.pm
  src/storage/wd/nas/snmp/mode/volumes.pm
  tests/storage/wd/nas/snmp/hardware.robot
  tests/storage/wd/nas/snmp/listvolumes.robot
  tests/storage/wd/nas/snmp/nas-wd.snmpwalk
  tests/storage/wd/nas/snmp/volumes.robot
Labels: enhancement, contribution, internal
