Repository centreon/centreon-plugins, pull requests merged in 2024-12, with the labels that each got.

#5299 CTOR-454 : New Plugin(apps::antivirus::skyhigh::webgateway::snmp)
  packaging/centreon-plugin-Applications-Antivirus-Skyhigh-Webgateway-Snmp/deb.json
  packaging/centreon-plugin-Applications-Antivirus-Skyhigh-Webgateway-Snmp/pkg.json
  packaging/centreon-plugin-Applications-Antivirus-Skyhigh-Webgateway-Snmp/rpm.json
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/clients.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/connections.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/detections.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/ftpstatistics.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/httpsstatistics.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/httpstatistics.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/system.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/mode/versions.pm
  src/apps/antivirus/skyhigh/webgateway/snmp/plugin.pm
  tests/resources/spellcheck/stopwords.txt
Labels: new, pack

#5304 CTOR-289 : Plugin(network::keysight::nvos::restapi): enhance ports mode and add license mode
  src/network/keysight/nvos/restapi/mode/license.pm
  src/network/keysight/nvos/restapi/mode/listdynamicfilters.pm
  src/network/keysight/nvos/restapi/mode/listports.pm
  src/network/keysight/nvos/restapi/mode/ports.pm
  src/network/keysight/nvos/restapi/plugin.pm
  tests/network/keysight/nvos/restapi/keysight.json
  tests/network/keysight/nvos/restapi/license.robot
  tests/network/keysight/nvos/restapi/ports.robot
  tests/resources/spellcheck/stopwords.txt
Labels: upload-artifacts

#5334 enh(ci): skip workflow when no change on PR
  .github/workflows/as400.yml
  .github/workflows/connector-vmware.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/get-environment.yml
  .github/workflows/nrpe.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-filesys-smbclient.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-keepass-reader.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plink.yml
  .github/workflows/plugins-selinux.yml
  .github/workflows/plugins.yml
  .github/workflows/set-pull-request-skip-label.yml
Labels: skip-workflow-plugins, skip-workflow-perl-json-path, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5319 Update pkg.json
  packaging/centreon-plugin-Hardware-Storage-Netapp-Ontap-Snmp/pkg.json
Labels: plugin, bugfix

#5358 doc(helps sections): Correct helps sections
  src/centreon/common/huawei/standard/snmp/mode/interfaces.pm
  src/centreon/plugins/output.pm
  src/network/aruba/cppm/snmp/mode/cpu.pm
  src/snmp_standard/mode/cpu.pm
  src/snmp_standard/mode/diskio.pm
  src/snmp_standard/mode/inodes.pm
  src/snmp_standard/mode/interfaces.pm
  src/snmp_standard/mode/listdiskspath.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5361 doc(output): fix the output.pm help section
  src/centreon/plugins/output.pm
Labels: skip-workflow-plugins

#5362 fix(packaging): bad path to plugin code
  packaging/centreon-plugin-Network-Huawei-Snmp/pkg.json
Labels: skip-workflow-plugins

#5363 fix(huawei-standard): bad path to huawei common code
  packaging/centreon-plugin-Network-Huawei-Snmp/pkg.json
Labels: upload-artifacts, skip-workflow-plugins

#5356 hardware::devices::video::axis::snmp::mode::components::fan - Fix map fan status - false positive
  src/hardware/devices/video/axis/snmp/mode/components/fan.pm
Labels: bugfix, in-backlog, contribution, external

#5366 fix(Plugin(video::axis): wrong psu status oid
  src/hardware/devices/video/axis/snmp/mode/components/fan.pm
  src/hardware/devices/video/axis/snmp/mode/components/psu.pm
Labels: skip-workflow-plugins

#5357 enh(meraki-cloudcontroller-restapi): add --filter-model to discovery mode
  src/network/cisco/meraki/cloudcontroller/restapi/mode/discovery.pm
Labels: skip-workflow-plugins

#5346 CTOR-1241: Plugin(storage::emc::datadomain::snmp) - Mode(cleaning) : Wrong output when cleaning is running
  src/storage/emc/datadomain/snmp/mode/cleaning.pm
  tests/storage/emc/datadomain/snmp/cleaning.robot
  tests/storage/emc/datadomain/snmp/slim-datadomain-cleaning-running.snmpwalk
  tests/storage/emc/datadomain/snmp/slim-datadomain.snmpwalk
Labels: skip-workflow-plugins

#5369 fix(sun-mgmt): the default plink command was not applied
  src/apps/salesforce/restapi/custom/api.pm
  src/hardware/server/sun/mgmt_cards/mode/showfaults.pm
  src/hardware/server/sun/mgmt_cards/mode/showfaulty.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins
