Repository centreon/centreon-plugins, pull requests merged in 2024-02, with the labels that each got.

#4860 enh(help): replace datas with data
  src/apps/protocols/http/mode/collection.pm
  src/apps/protocols/snmp/mode/cache.pm
  src/apps/protocols/snmp/mode/collection.pm
  src/apps/vmware/vcsa/snmp/mode/interfaces.pm
  src/apps/vmware/vcsa/snmp/mode/storage.pm
  src/centreon/common/bluearc/snmp/mode/interfaces.pm
  src/centreon/common/cisco/standard/snmp/mode/interfaces.pm
  src/centreon/common/fortinet/fortigate/snmp/mode/interfaces.pm
  src/centreon/common/h3c/snmp/mode/interfaces.pm
  src/centreon/common/ibm/nos/snmp/mode/disk.pm
  src/centreon/common/protocols/sql/mode/collection.pm
  src/hardware/devices/camera/optelecom/snmp/mode/interfaces.pm
  src/network/adva/fsp3000/snmp/mode/interfaces.pm
  src/network/aruba/cppm/snmp/mode/interfaces.pm
  src/network/atrica/snmp/mode/connections.pm
  src/network/brocade/snmp/mode/interfaces.pm
  src/network/cambium/cnpilot/snmp/mode/interfaces.pm
  src/network/cambium/epmp/snmp/mode/interfaces.pm
  src/network/chapsvision/crossing/snmp/mode/interfaces.pm
  src/network/dell/nseries/snmp/mode/interfaces.pm
  src/network/dlink/standard/snmp/mode/interfaces.pm
  src/network/enterasys/snmp/mode/interfaces.pm
  src/network/extreme/snmp/mode/interfaces.pm
  src/network/fortinet/fortiadc/snmp/mode/interfaces.pm
  src/network/fortinet/fortimail/snmp/mode/interfaces.pm
  src/network/fortinet/fortiswitch/snmp/mode/interfaces.pm
  src/network/hp/moonshot/snmp/mode/interfaces.pm
  src/network/hp/procurve/snmp/mode/interfaces.pm
  src/network/huawei/snmp/mode/interfaces.pm
  src/network/juniper/common/junos/mode/interfaces.pm
  src/network/lenovo/rackswitch/snmp/mode/interfaces.pm
  src/network/libraesva/snmp/mode/interfaces.pm
  src/network/libraesva/snmp/mode/storage.pm
  src/network/microsens/g6/snmp/mode/interfaces.pm
  src/network/mikrotik/snmp/mode/disk.pm
  src/network/mikrotik/snmp/mode/interfaces.pm
  src/network/mikrotik/snmp/mode/memory.pm
  src/network/mrv/optiswitch/snmp/mode/interfaces.pm
  src/network/netgear/sseries/snmp/mode/interfaces.pm
  src/network/nortel/standard/snmp/mode/interfaces.pm
  src/network/oneaccess/snmp/mode/interfaces.pm
  src/network/opengear/snmp/mode/interfaces.pm
  src/network/paloalto/snmp/mode/memory.pm
  src/network/raisecom/snmp/mode/interfaces.pm
  src/network/sonus/sbc/snmp/mode/interfaces.pm
  src/network/sonus/sbc/snmp/mode/storage.pm
  src/network/teldat/snmp/mode/interfaces.pm
  src/network/teltonika/snmp/mode/interfaces.pm
  src/network/viptela/snmp/mode/interfaces.pm
  src/os/picos/snmp/mode/interfaces.pm
  src/snmp_standard/mode/diskusage.pm
  src/snmp_standard/mode/interfaces.pm
  src/snmp_standard/mode/storage.pm
  src/storage/lenovo/iomega/snmp/mode/interfaces.pm
Labels: do-not-check-spelling

#4720 enh(mode): Rubrik RestAPI manage disco empty entries
  src/apps/backup/rubrik/restapi/mode/listjobs.pm
Labels: bugfix, in-backlog

#4848 fix(ci): fix breaking changes brought by upload/download artifacts version update
  .github/actions/merge-artifacts/action.yml
  .github/actions/package-nfpm/action.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-keepass-reader.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/plink.yml
Labels: dependencies, gha
