Repository centreon/centreon-plugins, pull requests merged in 2024-07, with the labels that each got.

#5088 Ctor 264 plugin database mysql mode databasesize change the way we calculate the fragmentation rate
  src/database/mysql/mode/databasessize.pm
Labels: breaking change

#5092 chore(deps): absorb 24.07 dependabot GitHub Actions updates
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
  .github/workflows/spellchecker.yml
Labels: dependencies, gha

#5103 Release 20240711
  .github/PULL_REQUEST_TEMPLATE.md
  .github/scripts/pod_spell_check.t
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
  .github/workflows/spellchecker.yml
  connectors/vmware/src/centreon/vmware/common.pm
  packaging/centreon-plugin-Network-Nokia-Isam-Snmp/deb.json
  packaging/centreon-plugin-Network-Nokia-Isam-Snmp/pkg.json
  packaging/centreon-plugin-Network-Nokia-Isam-Snmp/rpm.json
  src/apps/microsoft/hyperv/2012/local/mode/nodeintegrationservice.pm
  src/apps/protocols/http/mode/jsoncontent.pm
  src/apps/trendmicro/iwsva/snmp/plugin.pm
  src/centreon/common/powershell/hyperv/2012/nodeintegrationservice.pm
  src/database/mysql/mode/databasessize.pm
  src/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/listvpntunnels.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/networks.pm
  src/network/cisco/meraki/cloudcontroller/restapi/mode/vpntunnels.pm
  src/network/cisco/meraki/cloudcontroller/restapi/plugin.pm
  src/network/nokia/isam/snmp/mode/components/cardtemperature.pm
  src/network/nokia/isam/snmp/mode/components/resources.pm
  src/network/nokia/isam/snmp/mode/components/sfp.pm
  src/network/nokia/isam/snmp/mode/cpu.pm
  src/network/nokia/isam/snmp/mode/hardware.pm
  src/network/nokia/isam/snmp/mode/hubsapusage.pm
  src/network/nokia/isam/snmp/mode/listhubsap.pm
  src/network/nokia/isam/snmp/mode/memory.pm
  src/network/nokia/isam/snmp/plugin.pm
  src/os/windows/wsman/mode/listinterfaces.pm
  tests/resources/spellcheck/stopwords.t
  tests/robot/apps/microsoft/hyperv/2012/local/nodeintegrationservice-2022.json
  tests/robot/apps/microsoft/hyperv/2012/local/nodeintegrationservice.robot
  tests/robot/network/cisco/meraki/cloudcontroller/restapi/meraki.mockoon.json
  tests/robot/network/cisco/meraki/cloudcontroller/restapi/vpntunnels.robot
  tests/robot/os/linux/snmp/list-diskio.robot
  tests/robot/os/linux/snmp/os-linux-snmp.robot
Labels: do-not-spellcheck
