Repository centreon/centreon-plugins, pull requests merged in 2024-10, with the labels that each got.

#5171 [CTOR-775] - Fix apps::backup::rubrik::restapi::mode::jobs long output
  packaging/centreon-plugin-Applications-Rubrik-Restapi/deb.json
  packaging/centreon-plugin-Applications-Rubrik-Restapi/rpm.json
  src/apps/backup/rubrik/restapi/mode/jobs.pm
  tests/apps/backup/rubrik/restapi/applications-rubrik-restapi.json
  tests/apps/backup/rubrik/restapi/cache.robot
  tests/apps/backup/rubrik/restapi/jobs.robot
Labels: enhancement, bugfix, internal

#5199 CTOR - 815 : add(network::cisco::standard::snmp): add option --add-fc-fe-errors
  src/centreon/common/cisco/standard/snmp/mode/interfaces.pm
  tests/network/cisco/standard/snmp/interfaces.robot
  tests/network/cisco/standard/snmp/slim_cisco_fc_fe.snmpwalk
  tests/resources/spellcheck/stopwords.txt
Labels: enhancement, internal

#5236 Release 20241011
  as400/changelog
  as400/connector.as400/pom.xml
  as400/packaging/centreon-as400-daemon.yaml
Labels: do-not-spellcheck

#5239 fix(vmware-daemon): add missing centreonvault.pm file to packaging
  .github/workflows/connector-vmware.yml
  connectors/vmware/changelog
  connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml
  connectors/vmware/src/centreon/script/centreon_vmware.pm
Labels: upload-artifacts

#5184 enh(tests): new script to shrink and anonymize snmpwalks
  tests/os/linux/snmp/linux.snmpwalk
  tests/os/linux/snmp/processcount.robot
  tests/os/linux/snmp/uptime.robot
  tests/scripts/slim_walk.pl
Labels: do-not-spellcheck, internal

#5249 release 20241018
  as400/changelog
  as400/connector.as400.install/init-script/centreon-as400-sysconfig
  as400/connector.as400/pom.xml
  as400/packaging/centreon-as400-daemon.yaml
  connectors/vmware/changelog
  connectors/vmware/src/centreon/script/centreon_vmware.pm
  connectors/vmware/src/centreon/script/centreonvault.pm
  connectors/vmware/src/centreon/vmware/common.pm
Labels: do-not-spellcheck

#5253 fix(packaging): fix packaged files and java dependencies
  .github/workflows/as400.yml
  as400/changelog
  as400/connector.as400/pom.xml
  as400/packaging/centreon-as400-daemon.yaml
Labels: upload-artifacts
