Repository centreon/centreon-plugins, pull requests merged in 2024-08, with the labels that each got.

#5112 CTOR-757-plugin-apps-automation-ansible-tower-tests
  .gitignore
  src/apps/automation/ansible/tower/plugin.pm
  tests/resources/import.resource
  tests/resources/resources.resource
  tests/resources/spellcheck/stopwords.t
  tests/robot/apps/automation/ansible/tower/ansible_tower.json
  tests/robot/apps/automation/ansible/tower/hosts.robot
  tests/robot/apps/automation/ansible/tower/jobs.robot
  tests/robot/apps/microsoft/hyperv/2012/local/nodeintegrationservice.robot
  tests/robot/apps/protocols/http/collection-centreon-web.robot
  tests/robot/apps/protocols/snmp/collection-sputnik.robot
  tests/robot/apps/protocols/snmp/hashicorp-password-manager.robot
  tests/robot/cloud/azure/policyinsights/policystates/cloud-azure-policyinsights-policystates.robot
  tests/robot/hardware/devices/camera/avigilon/snmp/memory.robot
  tests/robot/hardware/devices/camera/avigilon/snmp/storage.robot
  tests/robot/hardware/devices/camera/avigilon/snmp/temperature.robot
  tests/robot/hardware/kvm/avocent/acs/8000/hardware-kvm-avocent-acs-8000.robot
  tests/robot/hardware/sensors/apc/snmp/hardware-sensors-apc-snmp.robot
  tests/robot/hardware/ups/inmatics/sputnik/snmp/hardware-ups-sputnik-snmp.robot
  tests/robot/hardware/ups/socomec/netvision/snmp/hardware-ups-socomec-netvision-snmp.robot
  tests/robot/hardware/ups/standard/snmp/hardware-ups-standard-snmp.robot
  tests/robot/network/aruba/instant/snmp/aruba-instant-ap-usage.robot
  tests/robot/network/cisco/meraki/cloudcontroller/restapi/vpntunnels.robot
  tests/robot/network/citrix/netscaler/snmp/mode/components/netscaler-health.robot
  tests/robot/network/fortinet/fortigate/snmp/network-fortinet-fortigate-snmp.robot
  tests/robot/network/teldat/snmp/cellsradio.robot
  tests/robot/network/teldat/snmp/cpu.robot
  tests/robot/network/teldat/snmp/memory.robot
  tests/robot/os/linux/snmp/list-diskio.robot
  tests/robot/os/linux/snmp/network-interfaces.robot
  tests/robot/os/windows/snmp/services.robot
  tests/robot/storage/datacore/restapi/storage-datacore-restapi.robot
  tests/robot/storage/synology/snmp/storage-synology-snmp.robot
Labels: do-not-spellcheck

#5124 enh(plugin): notification::microsoft::office365::teams::mode::alert - add workflow
  .github/actions/package-nfpm/action.yml
  src/notification/microsoft/office365/teams/custom/workflowapi.pm
  src/notification/microsoft/office365/teams/mode/alert.pm
  src/notification/microsoft/office365/teams/plugin.pm
Labels: upload-artifacts

#5140 chore(deps): absorb 24.08 dependabot GitHub Actions updates
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
Labels: dependencies, gha
