Repository centreon/centreon-plugins, pull requests merged in 2025-09, with the labels that each got.

#5715 Quanta refresh apps::monitoring::quanta::restapi
  src/apps/monitoring/quanta/restapi/custom/api.pm
  src/apps/monitoring/quanta/restapi/mode/listuserjourneys.pm
  src/apps/monitoring/quanta/restapi/mode/rum.pm
  src/apps/monitoring/quanta/restapi/mode/siteoverview.pm
  src/apps/monitoring/quanta/restapi/mode/userjourneyincidents.pm
  src/apps/monitoring/quanta/restapi/mode/userjourneystatistics.pm
  src/apps/monitoring/quanta/restapi/mode/webscenariosavailability.pm
  src/apps/monitoring/quanta/restapi/plugin.pm
  tests/apps/monitoring/quanta/restapi/listeuserjourneys.robot
  tests/apps/monitoring/quanta/restapi/quanta.mockoon.json
  tests/apps/monitoring/quanta/restapi/rum.robot
  tests/apps/monitoring/quanta/restapi/siteoverview.robot
  tests/apps/monitoring/quanta/restapi/userjourneyincidents.robot
  tests/apps/monitoring/quanta/restapi/userjourneystatistics.robot
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5712 CTOR-1439 Plugin(storage::netapp::ontap::restapi) - Mode(volumes) : Total space calculation error and missing snapshot info
  src/storage/netapp/ontap/restapi/mode/volumes.pm
  tests/storage/netapp/ontap/restapi/netapp.json
  tests/storage/netapp/ontap/restapi/volumes.robot
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5724 enh(cloud::kubernetes): update custom api pod to include default values.
  src/cloud/kubernetes/custom/api.pm
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5718 CTOR-761 Plugin(hardware::ups::apc::snmp) - Mode(sensors) : not compatible with APC Galaxy
  src/hardware/ups/apc/snmp/mode/components/sensor.pm
  src/hardware/ups/apc/snmp/mode/inputlines.pm
  src/hardware/ups/apc/snmp/mode/ntp.pm
  src/hardware/ups/apc/snmp/mode/outputlines.pm
  src/hardware/ups/apc/snmp/mode/sensors.pm
  src/hardware/ups/apc/snmp/plugin.pm
  tests/hardware/ups/apc/snmp/sensors.robot
  tests/hardware/ups/apc/snmp/ups-apc-galaxy.snmpwalk
  tests/hardware/ups/apc/snmp/ups-apc-sensors.snmpwalk
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5758 fix(rpm): update rpm digest algorythm to sha256
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5762 chore(packaging): increase package revision of rpm perl cpan libraries
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5765 CTOR-1937 Fix use centreon::plugin::misc
  src/storage/datacore/restapi/custom/api.pm
  src/storage/datacore/restapi/mode/alerts.pm
  src/storage/datacore/restapi/mode/monitorstatus.pm
Labels: skip-workflow-plugins

#5768 CTOR-776-new-pack-network-security-cato-networks-api
  packaging/centreon-plugin-Network-Security-Cato-Networks-Api/deb.json
  packaging/centreon-plugin-Network-Security-Cato-Networks-Api/pkg.json
  packaging/centreon-plugin-Network-Security-Cato-Networks-Api/rpm.json
  src/centreon/plugins/misc.pm
  src/centreon/plugins/statefile.pm
  src/network/security/cato/networks/api/custom/api.pm
  src/network/security/cato/networks/api/misc.pm
  src/network/security/cato/networks/api/mode/connectivity.pm
  src/network/security/cato/networks/api/mode/discovery.pm
  src/network/security/cato/networks/api/mode/events.pm
  src/network/security/cato/networks/api/mode/query.pm
  src/network/security/cato/networks/api/plugin.pm
  tests/network/security/cato/networks/api/cato-api.json
  tests/network/security/cato/networks/api/connectivity.robot
  tests/network/security/cato/networks/api/discovery.robot
  tests/network/security/cato/networks/api/events.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5779 enh(vmware8::esx): use statefiles to retain esx_id
  src/apps/vmware/vsphere8/esx/mode.pm
Labels: skip-workflow-plugins
