Repository centreon/centreon-plugins, pull requests merged in 2025-01, with the labels that each got.

#5377 fix(protocol-smtp): fixed chomp on undefined variable
  src/apps/protocols/smtp/lib/smtp.pm
Labels: skip-workflow-plugins

#5378 fix(colubris-snmp): fix labels to manage 15 minutes average thresholds
  src/network/colubris/snmp/mode/load.pm
Labels: skip-workflow-plugins

#5381 enh(backbox): add service discovery list-devices + new device-backup mode
  src/network/backbox/restapi/custom/api.pm
  src/network/backbox/restapi/mode/backup.pm
  src/network/backbox/restapi/mode/configstatus.pm
  src/network/backbox/restapi/mode/devicebackup.pm
  src/network/backbox/restapi/mode/intellicheck.pm
  src/network/backbox/restapi/mode/listdevices.pm
  src/network/backbox/restapi/plugin.pm
  tests/network/backbox/restapi/backbox.json
  tests/network/backbox/restapi/devicebackup.robot
  tests/network/backbox/restapi/listdevices.robot
Labels: skip-workflow-plugins

#5351 feat(aruba-snmp): add new stack mode
  src/network/aruba/aoscx/snmp/mode/stack.pm
  src/network/aruba/aoscx/snmp/plugin.pm
  tests/network/aruba/aoscx/snmp/slim_aoscx-stack.snmpwalk
  tests/network/aruba/aoscx/snmp/stack.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5091 fix(stormshield/api): mode interfaces wrong mapped values'
  src/network/stormshield/api/mode/interfaces.pm
Labels: bugfix

#5352 CTOR-1220 : Plugin(database::informix::snmp) - Mode(log-file-usage) : consider log files with state backedUpButNeeded as free space
  src/database/informix/snmp/mode/logfileusage.pm
  tests/database/informix/snmp/list-instances.robot
  tests/database/informix/snmp/logfile-usage.robot
  tests/database/informix/snmp/slim_informix-log.snmpwalk
Labels: skip-workflow-plugins

#5296 CTOR 1176: Plugin(os::freebsd::snmp) - Mode(storage): add default ZFS support + tests
  packaging/centreon-plugin-Operatingsystems-Freebsd-Snmp/deb.json
  packaging/centreon-plugin-Operatingsystems-Freebsd-Snmp/pkg.json
  packaging/centreon-plugin-Operatingsystems-Freebsd-Snmp/rpm.json
  src/os/freebsd/snmp/mode/storage.pm
  src/os/freebsd/snmp/plugin.pm
  tests/os/freebsd/snmp/freebsd.snmpwalk
  tests/os/freebsd/snmp/storage.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5359 CTOR-666-plugin-hardware-server-lenovo-xcc-snmp-mode-hardware-system-health-memory-and-cpu-table-not-checked
  src/hardware/server/lenovo/xcc/snmp/mode/components/cpu.pm
  src/hardware/server/lenovo/xcc/snmp/mode/components/health.pm
  src/hardware/server/lenovo/xcc/snmp/mode/components/memory.pm
  src/hardware/server/lenovo/xcc/snmp/mode/hardware.pm
  tests/README.md
  tests/hardware/server/lenovo/xcc/snmp/system-health-critical.snmpwalk
  tests/hardware/server/lenovo/xcc/snmp/system-health-nonRecoverable.snmpwalk
  tests/hardware/server/lenovo/xcc/snmp/system-health-ok.snmpwalk
  tests/hardware/server/lenovo/xcc/snmp/xcc-hardware-snmp.robot
  tests/resources/spellcheck/stopwords.txt
  tests/scripts/slim_walk.pl
Labels: skip-workflow-plugins

#5386 fix(server-lenovo-xcc-snmp): fixed hardware verbose output
  src/hardware/server/lenovo/xcc/snmp/mode/components/cpu.pm
  src/hardware/server/lenovo/xcc/snmp/mode/components/health.pm
  src/hardware/server/lenovo/xcc/snmp/mode/components/memory.pm
Labels: skip-workflow-plugins

#5379 feat(option): added an option to alter output and exit code (#5155)
  src/centreon/plugins/output.pm
  tests/os/linux/snmp/load.robot
Labels: skip-workflow-plugins

#5368 Plugin(storage::netapp::ontap::restapi): Enhance volumes mode and other enhancements
  src/storage/netapp/ontap/restapi/mode/aggregates.pm
  src/storage/netapp/ontap/restapi/mode/cluster.pm
  src/storage/netapp/ontap/restapi/mode/components/fru.pm
  src/storage/netapp/ontap/restapi/mode/hardware.pm
  src/storage/netapp/ontap/restapi/mode/listvolumes.pm
  src/storage/netapp/ontap/restapi/mode/luns.pm
  src/storage/netapp/ontap/restapi/mode/quotas.pm
  src/storage/netapp/ontap/restapi/mode/snapmirrors.pm
  src/storage/netapp/ontap/restapi/mode/volumes.pm
  tests/resources/spellcheck/stopwords.txt
  tests/storage/netapp/ontap/restapi/aggregates.robot
  tests/storage/netapp/ontap/restapi/cluster.robot
  tests/storage/netapp/ontap/restapi/hardware.robot
  tests/storage/netapp/ontap/restapi/luns.robot
  tests/storage/netapp/ontap/restapi/netapp.json
  tests/storage/netapp/ontap/restapi/quotas.robot
  tests/storage/netapp/ontap/restapi/snapmirrors.robot
  tests/storage/netapp/ontap/restapi/volumes.robot
Labels: skip-workflow-plugins

#5380 chore(deps): absorb 25.01 dependabot GitHub Actions updates
  .github/actions/merge-artifacts/action.yml
  .github/actions/package-delivery/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/test-plugins/action.yml
  .github/workflows/as400.yml
  .github/workflows/connector-vmware.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-filesys-smbclient.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
  .github/workflows/spellchecker.yml
Labels: dependencies, gha, skip-workflow-plugins, skip-workflow-perl-json-path, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5324 ci(cpan-libs): Add cpan libs tests
  .github/docker/packaging/Dockerfile.packaging-plugins-alma8
  .github/docker/packaging/Dockerfile.packaging-plugins-alma9
  .github/docker/packaging/Dockerfile.packaging-plugins-bookworm
  .github/docker/packaging/Dockerfile.packaging-plugins-bullseye
  .github/docker/packaging/Dockerfile.packaging-plugins-jammy
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-docker-builder-packaging-plugins, skip-workflow-perl-cpan-libraries

#5335 CTOR-102 [(New tests): network::cyberoam::snmp]
  .gitignore
  packaging/centreon-plugin-Network-Cyberoam-Snmp/deb.json
  packaging/centreon-plugin-Network-Cyberoam-Snmp/rpm.json
  src/network/cyberoam/snmp/mode/hastatus.pm
  src/network/cyberoam/snmp/mode/license.pm
  src/network/cyberoam/snmp/mode/listvpns.pm
  src/network/cyberoam/snmp/mode/vpnstatus.pm
  src/network/cyberoam/snmp/plugin.pm
  tests/network/cyberoam/snmp/ha-status.robot
  tests/network/cyberoam/snmp/interfaces.robot
  tests/network/cyberoam/snmp/license.robot
  tests/network/cyberoam/snmp/list-interfaces.robot
  tests/network/cyberoam/snmp/list-vpns.robot
  tests/network/cyberoam/snmp/memory.robot
  tests/network/cyberoam/snmp/requests.robot
  tests/network/cyberoam/snmp/services.robot
  tests/network/cyberoam/snmp/slim_sophos.snmpwalk
  tests/network/cyberoam/snmp/slim_sophos_no_ha.snmpwalk
  tests/network/cyberoam/snmp/storage.robot
  tests/network/cyberoam/snmp/vpn-status.robot
  tests/resources/spellcheck/stopwords.txt
Labels: internal, skip-workflow-perl-json-path, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5399 New test Mode (licenses)
  src/network/fortinet/fortigate/restapi/mode/licenses.pm
  tests/network/fortinet/fortigate/restapi/License-api.json
  tests/network/fortinet/fortigate/restapi/licenses.robot
Labels: skip-workflow-plugins
