Repository centreon/centreon-plugins, pull requests merged in 2025-08, with the labels that each got.

#5688 New pack LatenceTech: mode throughput
  src/apps/monitoring/latencetech/restapi/mode/connectivity.pm
  src/apps/monitoring/latencetech/restapi/mode/throughput.pm
  src/apps/monitoring/latencetech/restapi/plugin.pm
  tests/apps/monitoring/latencetech/restapi/connectivity.robot
  tests/apps/monitoring/latencetech/restapi/mockoon.json
  tests/apps/monitoring/latencetech/restapi/throughput.robot
Labels: skip-workflow-plugins

#5669 CTOR-1512 New Pack(network::forcepoint::sdwan::snmp)
  packaging/centreon-plugin-Network-Firewalls-Forcepoint-Sdwan-Snmp/deb.json
  packaging/centreon-plugin-Network-Firewalls-Forcepoint-Sdwan-Snmp/pkg.json
  packaging/centreon-plugin-Network-Firewalls-Forcepoint-Sdwan-Snmp/rpm.json
  src/network/forcepoint/sdwan/snmp/mode/clusterload.pm
  src/network/forcepoint/sdwan/snmp/mode/clusterstate.pm
  src/network/forcepoint/sdwan/snmp/mode/connections.pm
  src/network/forcepoint/sdwan/snmp/mode/diskusage.pm
  src/network/forcepoint/sdwan/snmp/mode/droppedpackets.pm
  src/network/forcepoint/sdwan/snmp/mode/listdisks.pm
  src/network/forcepoint/sdwan/snmp/mode/rejectedpackets.pm
  src/network/forcepoint/sdwan/snmp/plugin.pm
  src/snmp_standard/mode/cpudetailed.pm
  src/snmp_standard/mode/memory.pm
  src/snmp_standard/mode/swap.pm
  tests/network/forcepoint/sdwan/snmp/clusterload.robot
  tests/network/forcepoint/sdwan/snmp/clusterstate.robot
  tests/network/forcepoint/sdwan/snmp/connections.robot
  tests/network/forcepoint/sdwan/snmp/diskusage.robot
  tests/network/forcepoint/sdwan/snmp/droppedpackets.robot
  tests/network/forcepoint/sdwan/snmp/forcepoint.snmpwalk
  tests/network/forcepoint/sdwan/snmp/rejectedpackets.robot
  tests/network/forcepoint/sdwan/snmp/standard.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5639 CTOR-1200: Add OS and IPs information to autodiscovery module
  src/apps/proxmox/ve/restapi/custom/api.pm
  src/apps/proxmox/ve/restapi/mode/discovery.pm
  src/centreon/plugins/backend/http/curl.pm
  src/centreon/plugins/backend/http/lwp.pm
  src/centreon/plugins/misc.pm
  tests/apps/hashicorp/vault/restapi/proxmox-restapi.mockoon.json
  tests/apps/proxmox/ve/restapi/discovery.robot
  tests/apps/proxmox/ve/restapi/proxmox.mockoon.json
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5701 CTOR-1777 centreon_vmware change defaut log severity to error
  connectors/vmware/packaging/debian/centreon_vmware-default
  connectors/vmware/packaging/redhat/centreon_vmware-sysconfig
Labels: skip-workflow-connector-vmware, skip-workflow-plugins-analysis

#5674 Plugin(apps::redis::sentinel and database::redis) - Custom(cli): add certs and key parameters
  src/apps/redis/sentinel/custom/cli.pm
  src/database/redis/custom/cli.pm
  src/database/redis/custom/perlmod.pm
  tests/centreon/plugins/apps_redis_sentinel_parameters.t
  tests/centreon/plugins/database_redis_parameters.t
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5698 Plugin(apps::monitoring::iplabel::ekara::restapi) - Custom(api) : Add a new authentication way
  src/apps/monitoring/iplabel/ekara/restapi/custom/api.pm
  src/apps/monitoring/iplabel/ekara/restapi/mode/incidents.pm
  src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
  tests/monitoring/iplabel/ekara/restapi/incidents.robot
  tests/monitoring/iplabel/ekara/restapi/monitoring-iplabel-ekara.json
  tests/monitoring/iplabel/ekara/restapi/scenarios.robot
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5705 enh(nightly-ci): split created nightly ticket by type of failure
  .github/actions/create-jira-ticket/action.yml
  .github/actions/create-jira-ticket/nightly-ticket-template.json
  .github/workflows/plugins.yml
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5707 CTOR-1852 Plugin(apps::microsoft::hyperv::2012::local) - Mode(scvmm-discovery): Fix discovery stats
  src/apps/microsoft/hyperv/2012/local/mode/scvmmdiscovery.pm
  tests/apps/microsoft/hyperv/2012/local/scvmmdiscovery.json
  tests/apps/microsoft/hyperv/2012/local/scvmmdiscovery.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5695 chore(deps): absorb 2025-08 dependabot GitHub Actions updates
  .github/workflows/checkmarx-analysis.yml
Labels: dependencies, gha, skip-workflow-plugins-analysis

#5726 CTOR-1889 Do not try to start the perl connector if it is not installed
  tests/resources/connector.py
Labels: skip-workflow-plugins-analysis

#5714 CTOR-1865 Plugin(apps::proxmox::ve::restapi)
  tests/apps/proxmox/ve/restapi/discovery.robot
Labels: skip-workflow-plugins-analysis

#5723 CTOR-672 Plugin(os::linux::local) - Mode(ntp) : Adding support for timedatectl
  src/os/linux/local/mode/ntp.pm
  tests/os/linux/local/ntp.robot
  tests/os/linux/local/ntp_all_bin/chronyc
  tests/os/linux/local/ntp_all_bin/ntpq
  tests/os/linux/local/ntp_all_bin/timedatectl
  tests/os/linux/local/ntp_chrony_bin/chronyc
  tests/os/linux/local/ntp_ntpq_bin/ntpq
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5711 CTOR-1853 Plugin(cloud::docker::restapi) - Mode(container): fix memory usage calculation
  src/cloud/docker/restapi/mode/containerusage.pm
  tests/cloud/docker/restapi/container.robot
  tests/cloud/docker/restapi/docker.json
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5682 enh(apps::proxmox::ve::restapi): added options include-node-name and exclude-name CTOR-1848
  src/apps/proxmox/ve/restapi/custom/api.pm
  src/apps/proxmox/ve/restapi/mode/vmusage.pm
  tests/apps/proxmox/ve/restapi/discovery.robot
  tests/apps/proxmox/ve/restapi/proxmox.mockoon.json
  tests/apps/proxmox/ve/restapi/proxmox.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis
