Repository centreon/centreon-plugins, pull requests merged in 2025-02, with the labels that each got.

#5405 Fix cisco umbrella connections threshold name in --help output
  src/network/cisco/umbrella/snmp/mode/connectivity.pm
Labels: do-not-spellcheck, external

#5385 add(plugin): HAProxy Web Stats
  packaging/centreon-plugin-Applications-Haproxy-Web/deb.json
  packaging/centreon-plugin-Applications-Haproxy-Web/pkg.json
  packaging/centreon-plugin-Applications-Haproxy-Web/rpm.json
  src/apps/haproxy/web/custom/api.pm
  src/apps/haproxy/web/mode/backendusage.pm
  src/apps/haproxy/web/mode/frontendusage.pm
  src/apps/haproxy/web/mode/listobjects.pm
  src/apps/haproxy/web/plugin.pm
  tests/apps/haproxy/web/backendusage.robot
  tests/apps/haproxy/web/frontendusage.robot
  tests/apps/haproxy/web/mockoon.json
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5425 help(cyberoam-snmp): remove uppercase chars in options
  src/network/cyberoam/snmp/mode/vpnstatus.pm
  tests/network/cyberoam/snmp/vpn-status.robot
Labels: skip-workflow-plugins

#5426 enh(network::fortinet::fortigate::restapi): rebuild to add option and counter last-update CTOR-1126
  src/network/fortinet/fortigate/restapi/mode/licenses.pm
Labels: skip-workflow-plugins

#5421 Ctor-1322 enh(add new test mode)network::fortinet::fortigate::snmp, Mode(sdwan)
  src/centreon/common/fortinet/fortigate/snmp/mode/sdwan.pm
  tests/network/fortinet/fortigate/snmp/fortinet-fortigate.snmpwalk
  tests/network/fortinet/fortigate/snmp/sdawn.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5429 enh(apps::monitoring::iplabel::ekara::restapi): change status match and timeframe option default value CTOR-1387
  src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5430 enh(apps::monitoring::iplabel::ekara::restapi): change status match and timeframe option default value CTOR-1387
  src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
Labels: skip-workflow-plugins

#5436 fix(release): use new version scheme for plugin release tags
  .github/workflows/plugins.yml
Labels: skip-workflow-plugins

#5435 fix(release): use new version scheme for plugin release tags
  .github/workflows/plugins.yml
Labels: skip-workflow-plugins

#5434 fix(podman): pod-status mode
  src/apps/podman/restapi/custom/api.pm
  tests/apps/podman/restapi/podman.json
Labels: skip-workflow-plugins

#5437 fix(podman): pod-status mode
  src/apps/podman/restapi/custom/api.pm
  tests/apps/podman/restapi/podman.json
Labels: skip-workflow-plugins

#5438 Release 20250201
  .github/workflows/plugins.yml
  src/apps/podman/restapi/custom/api.pm
  tests/apps/podman/restapi/podman.json
Labels: do-not-spellcheck, skip-workflow-plugins

#5444 fix(packaging): fix dependecy listing for perl-cpan-libraries (#5442)
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5445 Release 20250202
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5403 Ctor 1218 plugin storage purestorage
  src/storage/purestorage/flasharray/v2/restapi/mode/alerts.pm
  tests/storage/purestorage/flasharray/v2/restapi/alerts.robot
  tests/storage/purestorage/flasharray/v2/restapi/mokoon.json
Labels: skip-workflow-plugins

#5452 feat(vmware8-esx): add ability to get stats + cpu
  src/apps/vmware/vsphere8/custom/api.pm
  src/apps/vmware/vsphere8/esx/mode/cpu.pm
  src/apps/vmware/vsphere8/esx/plugin.pm
  tests/apps/vmware/vsphere8/api.t
  tests/apps/vmware/vsphere8/esx/cpu-curl.robot
  tests/apps/vmware/vsphere8/esx/cpu-lwp.robot
  tests/apps/vmware/vsphere8/esx/vmware8-restapi.mockoon.json
  tests/resources/resources.resource
Labels: upload-artifacts, skip-workflow-plugins

#5395 Fix(storage::netapp::ontap::restapi::plugin) - Mode(volumes,cluster,aggregates,hardware) : Issue on metric.* field not included + fix hardware API requests
  src/storage/netapp/ontap/restapi/mode/hardware.pm
  tests/storage/netapp/ontap/restapi/aggregates.robot
  tests/storage/netapp/ontap/restapi/cluster.robot
  tests/storage/netapp/ontap/restapi/netapp.json
  tests/storage/netapp/ontap/restapi/volumes.robot
Labels: skip-workflow-plugins

#5342 Plugin(cloud::azure::network::vpngateway::plugin) - Mode(vpn-gateway-status) : Wrong variable assignment
  src/cloud/azure/network/vpngateway/mode/health.pm
  src/cloud/azure/network/vpngateway/mode/sitetraffic.pm
  src/cloud/azure/network/vpngateway/mode/tunneltraffic.pm
  src/cloud/azure/network/vpngateway/mode/vpngatewaystatus.pm
  tests/cloud/azure/network/vpngateway/vpngatewaystatus.json
  tests/cloud/azure/network/vpngateway/vpngatewaystatus.robot
Labels: skip-workflow-plugins

#5397 Plugin(hardware::pdu::raritan::snmp): fix sensors state for PDU > 4.x when an outlet sensor is off
  src/hardware/pdu/raritan/snmp/mode/components/resources.pm
  src/hardware/pdu/raritan/snmp/mode/components/sensor.pm
  tests/hardware/pdu/raritan/snmp/inletsensors.robot
  tests/hardware/pdu/raritan/snmp/outletsensors.robot
  tests/hardware/pdu/raritan/snmp/raritan.snmpwalk
Labels: skip-workflow-plugins

#5470 enh(ci): migrate runners to arc v2
  .github/workflows/actionlint.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plugins.yml
Labels: skip-workflow-plugins, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests
