Repository centreon/centreon-plugins, pull requests merged in 2025-05, with the labels that each got.

#5559 fix(cloud::azure::storage::storagesync): fixed recalls mode by removing deprecated StorageSyncRecallIOTotalSizeBytes metric CTOR-1614
  src/cloud/azure/storage/storagesync/mode/filessync.pm
  src/cloud/azure/storage/storagesync/mode/recalls.pm
  src/cloud/azure/storage/storagesync/mode/serverstatus.pm
Labels: skip-workflow-plugins

#5553 Enh (network::mikrotik::snmp(New mode lte-interfaces and list-lte-interfaces))
  src/network/mikrotik/snmp/mode/listlteinterfaces.pm
  src/network/mikrotik/snmp/mode/lteinterfaces.pm
  src/network/mikrotik/snmp/plugin.pm
  tests/network/mikrotik/snmp/listlteinterfaces.robot
  tests/network/mikrotik/snmp/lteinterfaces.robot
  tests/network/mikrotik/snmp/mikrotik-chateau-lte6.snmpwalk
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5576 ENH Plugin(storage::purestorage::flasharray::v2::restapi) - Mode(arrays): Extend perf counter
  src/storage/purestorage/flasharray/v2/restapi/mode/arrays.pm
  tests/resources/spellcheck/stopwords.txt
  tests/storage/purestorage/flasharray/v2/restapi/Mockoonarray.json
  tests/storage/purestorage/flasharray/v2/restapi/array.robot
Labels: skip-workflow-plugins

#5577 fix(cloud::azure::storage::storagesync): fixed thresholds options help
  src/cloud/azure/storage/storagesync/mode/recalls.pm
Labels: skip-workflow-plugins

#5567 CTOR-293: New pack operatingsystems f5 os snmp
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/deb.json
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/pkg.json
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/rpm.json
  src/os/f5os/snmp/mode/cpuusage.pm
  src/os/f5os/snmp/mode/hardware.pm
  src/os/f5os/snmp/mode/memory.pm
  src/os/f5os/snmp/plugin.pm
  tests/os/f5os/snmp/cpu-usage.robot
  tests/os/f5os/snmp/f5os.snmpwalk
  tests/os/f5os/snmp/hardware.robot
  tests/os/f5os/snmp/memory.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5565 ENH plugin(network::cisco::smallbusiness::standard::snmp): add stack mode
  src/centreon/common/cisco/smallbusiness/snmp/mode/stack.pm
  src/network/cisco/smallbusiness/standard/snmp/plugin.pm
  tests/network/cisco/smallbusiness/snmp/stack.robot
  tests/network/cisco/smallbusiness/snmp/stack.snmpwalk
Labels: skip-workflow-plugins

#5563 enh(network::stormshield::api): fix help section CTOR-628
  src/network/stormshield/api/mode/vpntunnels.pm
Labels: skip-workflow-plugins

#5582 enh(apps::mq::ibmmq::mqi): remove perl lib msqseries dependency
  packaging/centreon-plugin-Applications-Ibmmq-Mqi/deb.json
  packaging/centreon-plugin-Applications-Ibmmq-Mqi/rpm.json
Labels: skip-workflow-plugins

#5581 help(storage::emc::datadomain::snmp::mode::alerts): fix option description
  src/storage/emc/datadomain/snmp/mode/alerts.pm
Labels: skip-workflow-plugins

#5583 doc(f5OS): fix help message
  src/os/f5os/snmp/mode/hardware.pm
Labels: skip-workflow-plugins

#5589 CTOR-1634: Plugin(database::oracle) - Segmentation Fault with `glibc` Latest Version
  src/database/oracle/dbi.pm
Labels: skip-workflow-plugins

#5590 Release 20250501
  .github/workflows/gitleaks.yml
  connectors/vmware/changelog
  connectors/vmware/packaging/scripts/postinstall.sh
  connectors/vmware/src/centreon/script/centreon_vmware.pm
  connectors/vmware/src/centreon/vmware/common.pm
  src/database/oracle/dbi.pm
Labels: do-not-spellcheck, skip-workflow-plugins, skip-workflow-connector-vmware

#5588 ci(secu): deploy checkmarx
  .github/CODEOWNERS
  .github/workflows/checkmarx-analysis.yml
  .github/workflows/plugins-analysis.yml
Labels: skip-workflow-plugins-analysis

#5585 fix(vmware-sdk): remove perl-vmware-sdk workflow
  .github/workflows/perl-vmware-vsphere.yml
  connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml
  dependencies/perl-vmware-vsphere/packaging/perl-vmware-vsphere.yaml
Labels: upload-artifacts, skip-workflow-connector-vmware, skip-workflow-plugins-analysis
