Repository centreon/centreon-plugins, pull requests merged in 2025-04, with the labels that each got.

#5485 chore(deps): absorb 2025-03 dependabot GitHub Actions updates
  .github/actions/merge-artifacts/action.yml
  .github/actions/package-delivery/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/test-plugins/action.yml
  .github/workflows/as400.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-filesys-smbclient.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
Labels: dependencies, gha

#5534 fix(apps::eclipse::mosquitto::mqtt): mode numeric-value
  src/apps/eclipse/mosquitto/mqtt/mode/clients.pm
  src/apps/eclipse/mosquitto/mqtt/mode/messages.pm
  src/apps/eclipse/mosquitto/mqtt/mode/numericvalue.pm
  src/apps/eclipse/mosquitto/mqtt/mode/uptime.pm
  tests/apps/eclipse/mosquitto/mqtt/clients.robot
  tests/apps/eclipse/mosquitto/mqtt/messages.robot
  tests/apps/eclipse/mosquitto/mqtt/numeric-value.robot
  tests/apps/eclipse/mosquitto/mqtt/string-value.robot
  tests/apps/eclipse/mosquitto/mqtt/uptime.robot
Labels: skip-workflow-plugins

#5492 fix(apps::backup::veeam::local): update jobstatus help section
  src/apps/backup/veeam/local/mode/jobstatus.pm
Labels: internal, skip-workflow-plugins

#5448 quick fix
  src/network/aruba/aoscx/snmp/mode/hardware.pm
Labels: skip-workflow-plugins

#5537 chore(deps): absorb 2025-04 dependabot GitHub Actions updates
  .github/actions/merge-artifacts/action.yml
  .github/actions/package-delivery/action.yml
  .github/actions/package-nfpm/action.yml
  .github/actions/test-cpan-libs/action.yml
  .github/actions/test-plugins/action.yml
  .github/workflows/as400.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/get-environment.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-filesys-smbclient.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plink.yml
  .github/workflows/plugins.yml
Labels: dependencies, gha, skip-workflow-plugins, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5523 doc(dev): add plugins sequence diagram
  doc/en/developer/plugins_advanced.md
  doc/en/developer/sequence_diagram.md
  doc/en/developer/sequence_diagram.mmd
Labels: internal

#5558 test(gorgone-unit): add gorgone deps to run new unit tests.
  .github/docker/unit-tests/Dockerfile.unit-tests-alma8
  .github/docker/unit-tests/Dockerfile.unit-tests-alma9
  .github/docker/unit-tests/Dockerfile.unit-tests-bookworm
  .github/docker/unit-tests/Dockerfile.unit-tests-bullseye
  .github/docker/unit-tests/Dockerfile.unit-tests-jammy
  .github/docker/unit-tests/Dockerfile.unit-tests-noble
Labels: skip-workflow-docker-builder-unit-tests

#5549 ENH(New mode: battery)-(netvision5 and netvision6) hardware::ups::socomec::netvision::snmp
  src/hardware/ups/socomec/netvision/snmp/mode/battery.pm
  tests/hardware/ups/socomec/netvision/snmp/battery-netvision5.robot
  tests/hardware/ups/socomec/netvision/snmp/battery-netvision6.robot
  tests/hardware/ups/socomec/netvision/snmp/battery.snmpwalk
  tests/hardware/ups/socomec/netvision/snmp/hardware-ups-socomec-netvision-snmp.robot
  tests/hardware/ups/socomec/netvision/snmp/netvision5.snmpwalk
  tests/hardware/ups/socomec/netvision/snmp/netvision6.snmpwalk
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5556 CTOR-1564: implement cpu-usage
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/deb.json
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/pkg.json
  packaging/centreon-plugin-Operatingsystems-F5os-Snmp/rpm.json
  src/os/f5os/snmp/mode/cpuusage.pm
  src/os/f5os/snmp/plugin.pm
  tests/os/f5os/snmp/cpu-usage.robot
  tests/os/f5os/snmp/f5os.snmpwalk
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5566 enh(cloud::azure::storage::storagesync): added filter-metric help section CTOR-1614
  src/cloud/azure/storage/storagesync/mode/filessync.pm
  src/cloud/azure/storage/storagesync/mode/recalls.pm
  src/cloud/azure/storage/storagesync/mode/serverstatus.pm
Labels: skip-workflow-plugins

#5562 CTOR-1566: implement hardware mode
  src/os/f5os/snmp/mode/hardware.pm
  src/os/f5os/snmp/plugin.pm
  tests/os/f5os/snmp/hardware.robot
Labels: skip-workflow-plugins
