Repository centreon/centreon-plugins, pull requests merged in 2025-07, with the labels that each got.

#5648 CTOR-711: Custom(cloud::azure::custom::api) Add option to choose cost-metric
  src/centreon/plugins/mode.pm
  src/cloud/azure/custom/api.pm
  src/cloud/azure/management/costs/mode/budgets.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5631 fix(storage::emc::datadomain::snmp): fixed issue in cleaning mode when default value for timezone is empty leading to unknown CTOR-1700
  src/storage/emc/datadomain/snmp/mode/cleaning.pm
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5645 CTOR-1558: Enhance standby mode and extra parameters support
  src/apps/hashicorp/vault/restapi/mode/health.pm
  tests/apps/hashicorp/vault/restapi/hashicorp-health.mockoon.json
  tests/apps/hashicorp/vault/restapi/hashicorp-health.robot
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5598 CTOR-1656-move-centreon-plugins-sudoers-to-centreon-plugin-repository
  .github/workflows/centreon-plugins-sudoers.yml
  dependencies/centreon-plugins-sudoers/centreon-plugins-sudoers.yaml
  dependencies/centreon-plugins-sudoers/sudoersCentreonPlugins
  tests/apps/nmap/cli/discovery.robot
  tests/centreon/plugins/misc.t
  tests/resources/resources.resource
Labels: upload-artifacts, skip-workflow-plugins, skip-workflow-plugins-analysis, skip-workflow-centreon-plugins-sudoers

#5634 CTOR-1248: Display full curl command in log
  .github/docker/unit-tests/Dockerfile.unit-tests-alma8
  .github/docker/unit-tests/Dockerfile.unit-tests-alma9
  .github/docker/unit-tests/Dockerfile.unit-tests-bookworm
  .github/docker/unit-tests/Dockerfile.unit-tests-bullseye
  .github/docker/unit-tests/Dockerfile.unit-tests-jammy
  .github/docker/unit-tests/Dockerfile.unit-tests-noble
  .github/packaging/centreon-plugin.yaml.template
  .github/scripts/plugins-source.container.pl
  src/centreon/plugins/backend/http/curl.pm
  src/centreon/plugins/curllogger.pm
  src/centreon/plugins/http.pm
  tests/centreon/plugins/curllogger.cookies
  tests/centreon/plugins/curllogger.t
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-docker-builder-unit-tests, skip-workflow-plugins-analysis

#5657 CTOR-382: Plugin(apps::apache::serverstatus) - Modes (requests - slotstates) : Add nlabel and force new perfdata
  src/apps/apache/serverstatus/mode/requests.pm
  src/apps/apache/serverstatus/mode/slotstates.pm
  tests/apps/apache/serverstatus/requests.robot
  tests/apps/apache/serverstatus/serverstatus.mockoon.json
  tests/apps/apache/serverstatus/slotstates.robot
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5667 fix(release): update plugins version to 20250700
  .version.plugins
Labels: skip-workflow-plugins-analysis

#5671 fix(plugin) hardware::server::hp::ilo::restapi - Exclude enclosure
  src/centreon/common/redfish/restapi/mode/components/chassis.pm
Labels: skip-workflow-plugins, skip-workflow-plugins-analysis

#5085 enh(notification::email): Allow a custom pathname in alert mode
  src/notification/email/mode/alert.pm
Labels: contribution, skip-workflow-plugins, skip-workflow-plugins-analysis

#5683 New pack LatenceTech : mode discovery
  src/apps/monitoring/latencetech/restapi/mode/discovery.pm
  src/apps/monitoring/latencetech/restapi/plugin.pm
  tests/apps/monitoring/latencetech/restapi/discovery.robot
  tests/apps/monitoring/latencetech/restapi/mockoon.json
Labels: skip-workflow-plugins

#5686 New pack LatenceTech: mode radio
  src/apps/monitoring/latencetech/restapi/mode/radio.pm
  src/apps/monitoring/latencetech/restapi/plugin.pm
  tests/apps/monitoring/latencetech/restapi/mockoon.json
  tests/apps/monitoring/latencetech/restapi/radio.robot
Labels: skip-workflow-plugins
