Repository centreon/centreon-plugins, pull requests merged in 2025-03, with the labels that each got.

#5475 fix(as400): fix previous pending request
  src/os/as400/connector/custom/api.pm
  src/os/as400/connector/mode/disks.pm
  src/os/as400/connector/mode/jobs.pm
  src/os/as400/connector/mode/listdisks.pm
  src/os/as400/connector/mode/listsubsystems.pm
  src/os/as400/connector/mode/subsystems.pm
Labels: skip-workflow-plugins

#5472 fix(storage::purestorage::flasharray::v2::restapi): fixed wrong option filter-resolution in arrays and volumes mode CTOR-1218
  src/storage/purestorage/flasharray/v2/restapi/mode/arrays.pm
  src/storage/purestorage/flasharray/v2/restapi/mode/volumes.pm
Labels: skip-workflow-plugins

#5449 Ctor 1237 plugin network fortinet fortigate snmp mode vpn add counter for ip sec tunnels
  src/centreon/common/fortinet/fortigate/snmp/mode/vpn.pm
  tests/network/fortinet/fortigate/snmp/fortigate-vpn.snmpwalk
  tests/network/fortinet/fortigate/snmp/vpn.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5467 CTOR-1294-plugin-hardware-server-cisco-ucs-snmp-mode-equipment-wrong-count-when-using-threshold-overload-option
  src/hardware/server/cisco/ucs/snmp/mode/components/memory.pm
  src/hardware/server/cisco/ucs/snmp/mode/equipment.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5482 feat(vmware8-esx): add MVP modes
  src/apps/vmware/vsphere8/custom/api.pm
  src/apps/vmware/vsphere8/esx/mode.pm
  src/apps/vmware/vsphere8/esx/mode/cpu.pm
  src/apps/vmware/vsphere8/esx/mode/discovery.pm
  src/apps/vmware/vsphere8/esx/mode/hoststatus.pm
  src/apps/vmware/vsphere8/esx/mode/memory.pm
  src/apps/vmware/vsphere8/esx/mode/power.pm
  src/apps/vmware/vsphere8/esx/plugin.pm
  tests/apps/vmware/vsphere8/api.t
  tests/apps/vmware/vsphere8/esx/cpu-curl.robot
  tests/apps/vmware/vsphere8/esx/cpu-lwp.robot
  tests/apps/vmware/vsphere8/esx/host-status.robot
  tests/apps/vmware/vsphere8/esx/memory.robot
  tests/apps/vmware/vsphere8/esx/power.robot
  tests/apps/vmware/vsphere8/esx/vmware8-restapi.mockoon.json
  tests/resources/resources.resource
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5453 fix(storage::emc::datadomain::snmp): fixed cleaning mode by adding timezone option CTOR-1415
  src/storage/emc/datadomain/snmp/mode/cleaning.pm
  tests/storage/emc/datadomain/snmp/cleaning.robot
  tests/storage/emc/datadomain/snmp/slim-datadomain-cleaning-ok.snmpwalk
Labels: skip-workflow-plugins

#5411 Ctor 1323 ENH(new mode): test-Plugin(hardware::server::cisco::ucs::snmp)- Mode(equipment)
  tests/hardware/server/cisco/ucs/snmp/equipement.robot
  tests/hardware/server/cisco/ucs/snmp/slim-ucs-equipment.snmpwalk
Labels: skip-workflow-plugins, skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5469 Ctor 1018 perl json path dependencies issue
  .github/actions/test-cpan-libs/action.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-crypt-argon2.yml
  .github/workflows/perl-json-path.yml
  .github/workflows/perl-libssh-session.yml
  .github/workflows/perl-net-curl.yml
  dependencies/perl-crypt-argon2/perl-crypt-argon2.yaml
  dependencies/perl-json-path/perl-json-path.yaml
  dependencies/perl-libssh-session/perl-libssh-session.yaml
  dependencies/perl-net-curl/perl-net-curl.yaml
  tests/cpan-libraries/crypt-argon2.pl
  tests/cpan-libraries/json-path.pl
  tests/cpan-libraries/libssh-session.pl
  tests/cpan-libraries/net-curl.pl
Labels: skip-workflow-perl-cpan-libraries

#5476 enh(as400): add ssl connection option
  .github/docker/packaging/Dockerfile.packaging-plugins-java-alma8
  .github/docker/packaging/Dockerfile.packaging-plugins-java-alma9
  .github/docker/packaging/Dockerfile.packaging-plugins-java-bookworm
  .github/docker/packaging/Dockerfile.packaging-plugins-java-bullseye
  .github/docker/packaging/Dockerfile.packaging-plugins-java-jammy
  .github/workflows/as400.yml
  .github/workflows/get-environment.yml
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/AbstractHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/CommandHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/DiskHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/JobHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/JobQueueHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/SubSystemHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/SystemHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/disk/QyaspolYasp0300PcmlHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/msgqueue/CachedMessageQueueHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/msgqueue/MessageQueueHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/wrkprb/WorkWithProblemHandler.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/client/IClient.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/client/impl/AbstractClient.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/check/CheckDispatcher.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/check/InputData.java
  as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/client/impl/ClientDispatcherImpl.java
  as400/connector.as400/src/test/java/com/centreon/connector/as400/check/handler/impl/SystemHandlerTest.java
  src/os/as400/connector/custom/api.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins, skip-workflow-docker-builder-packaging-plugins, skip-workflow-as400

#5454 Ctor 1397 plugin network aruba aoscx snmp add spanning tree and discovery modes
  packaging/centreon-plugin-Network-Aruba-Aoscx-Snmp/pkg.json
  src/network/aruba/aoscx/snmp/plugin.pm
  tests/network/aruba/aoscx/snmp/hardware.robot
  tests/network/aruba/aoscx/snmp/interfaces.robot
  tests/network/aruba/aoscx/snmp/list-interfaces.robot
  tests/network/aruba/aoscx/snmp/list-spanning-trees.robot
  tests/network/aruba/aoscx/snmp/slim_aoscx-spanning-tree.snmpwalk
  tests/network/aruba/aoscx/snmp/spanning-tree.robot
  tests/network/aruba/aoscx/snmp/uptime.robot
Labels: skip-workflow-plugins

#5499 Release 20250302
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5503 fix(cpan-libraries): Add revision to update libraries
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5505 fix(packaging): handle specific case of libssh-session packaging name
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5506 Release 20250303
  .github/workflows/perl-cpan-libraries.yml
Labels: skip-workflow-perl-cpan-libraries

#5495 fix(storage::ibm::fs900::snmp): remove wrong default value all CTOR-544
  src/storage/ibm/fs900/snmp/mode/hardware.pm
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5511 chore(ci): update tj-actions/changed-files to 46.0.1 for branch develop
  .github/workflows/get-environment.yml
Labels: gha

#5497 feat: add noble to ci packaging and delivery
  .github/actions/package-delivery/action.yml
  .github/actions/parse-distrib/action.yml
  .github/actions/promote-to-stable/action.yml
  .github/docker/packaging/Dockerfile.packaging-plugins-java-noble
  .github/docker/packaging/Dockerfile.packaging-plugins-noble
  .github/docker/testing/Dockerfile.testing-plugins-noble
  .github/docker/unit-tests/Dockerfile.unit-tests-noble
  .github/workflows/as400.yml
  .github/workflows/connector-vmware.yml
  .github/workflows/docker-builder-packaging-plugins.yml
  .github/workflows/docker-builder-testing-plugins.yml
  .github/workflows/docker-builder-unit-tests.yml
  .github/workflows/get-environment.yml
  .github/workflows/nrpe.yml
  .github/workflows/perl-cpan-libraries.yml
  .github/workflows/perl-filesys-smbclient.yml
  .github/workflows/perl-keepass-reader.yml
  .github/workflows/perl-openwsman.yml
  .github/workflows/perl-vmware-vsphere.yml
  .github/workflows/plugins.yml
Labels: skip-workflow-docker-builder-packaging-plugins, skip-workflow-docker-builder-testing-plugins, skip-workflow-perl-cpan-libraries, skip-workflow-docker-builder-unit-tests

#5501 enh(counters/iplabe-ekara): allow to sort instances on attribute instead of instance key
  src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
  src/centreon/plugins/templates/counter.pm
  tests/cloud/aws/cloudtrail/checktrailstatus.robot
  tests/cloud/aws/cloudtrail/countevents.robot
  tests/monitoring/iplabel/ekara/restapi/monitoring-iplabel-ekara.json
  tests/monitoring/iplabel/ekara/restapi/scenarios.robot
  tests/resources/resources.resource
Labels: skip-workflow-plugins

#5516 fix(ci): add missing image + fix path for tests on noble
  .github/actions/test-plugins/action.yml
  .github/docker/testing/Dockerfile.testing-plugins-alma8
  .github/docker/testing/Dockerfile.testing-plugins-alma9
  .github/docker/testing/Dockerfile.testing-plugins-bookworm
  .github/docker/testing/Dockerfile.testing-plugins-bullseye
  .github/docker/testing/Dockerfile.testing-plugins-jammy
  .github/docker/testing/Dockerfile.testing-plugins-noble
  .github/workflows/plugins.yml
Labels: skip-workflow-plugins, skip-workflow-docker-builder-testing-plugins

#5514 Ctor 1452 plugin network fortinet fortigate snmp new modes switch usage and switches discovery
  src/centreon/common/fortinet/fortigate/snmp/mode/listswitches.pm
  src/centreon/common/fortinet/fortigate/snmp/mode/switchusage.pm
  src/network/fortinet/fortigate/snmp/plugin.pm
  tests/network/fortinet/fortigate/snmp/list-switches.robot
  tests/network/fortinet/fortigate/snmp/slim_fortigate-switches.snmpwalk
  tests/network/fortinet/fortigate/snmp/switch-usage.robot
Labels: skip-workflow-plugins

#5510 enh(vmware8-esx): add swap, diskio and network + tests
  src/apps/vmware/vsphere8/esx/mode/cpu.pm
  src/apps/vmware/vsphere8/esx/mode/diskio.pm
  src/apps/vmware/vsphere8/esx/mode/memory.pm
  src/apps/vmware/vsphere8/esx/mode/network.pm
  src/apps/vmware/vsphere8/esx/mode/power.pm
  src/apps/vmware/vsphere8/esx/mode/swap.pm
  src/apps/vmware/vsphere8/esx/plugin.pm
  tests/apps/vmware/vsphere8/esx/cpu-curl.robot
  tests/apps/vmware/vsphere8/esx/cpu-lwp.robot
  tests/apps/vmware/vsphere8/esx/diskio.robot
  tests/apps/vmware/vsphere8/esx/memory.robot
  tests/apps/vmware/vsphere8/esx/network.robot
  tests/apps/vmware/vsphere8/esx/power.robot
  tests/apps/vmware/vsphere8/esx/swap.robot
  tests/apps/vmware/vsphere8/esx/vmware8-restapi.mockoon.json
Labels: skip-workflow-plugins

#5489 Ctor 1321 plugin apps backup veeam vbem restapi mode jobs list jobs handle replication jobs
  src/apps/backup/veeam/vbem/restapi/custom/api.pm
  src/apps/backup/veeam/vbem/restapi/mode/jobs.pm
  src/apps/backup/veeam/vbem/restapi/mode/listjobs.pm
  tests/apps/backup/veeam/vbem/restapi/jobs.robot
  tests/apps/backup/veeam/vbem/restapi/list-jobs.robot
  tests/apps/backup/veeam/vbem/restapi/restapi.json
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5518 feat(exense-step-restapi): new plugin to monitor plans executions + tests
  packaging/centreon-plugin-Applications-Exense-Step-Restapi/deb.json
  packaging/centreon-plugin-Applications-Exense-Step-Restapi/pkg.json
  packaging/centreon-plugin-Applications-Exense-Step-Restapi/rpm.json
  src/apps/exense/step/restapi/custom/api.pm
  src/apps/exense/step/restapi/mode/listplans.pm
  src/apps/exense/step/restapi/mode/listtenants.pm
  src/apps/exense/step/restapi/mode/plans.pm
  src/apps/exense/step/restapi/plugin.pm
  tests/apps/exense/step/restapi/list-plans.robot
  tests/apps/exense/step/restapi/list-tenants.robot
  tests/apps/exense/step/restapi/mockoon.json
  tests/apps/exense/step/restapi/plans.robot
  tests/resources/spellcheck/stopwords.txt
Labels: skip-workflow-plugins

#5515 feat(fortinet-fortigate-restapi): add certificates mode + tests
  src/network/fortinet/fortigate/restapi/mode/certificates.pm
  src/network/fortinet/fortigate/restapi/plugin.pm
  tests/network/fortinet/fortigate/restapi/certificates.json
  tests/network/fortinet/fortigate/restapi/certificates.robot
Labels: skip-workflow-plugins, skip-workflow-docker-builder-testing-plugins

#5471 feat(f5-bigip-snmp): add cpuusage mode + tests
  src/network/f5/bigip/snmp/mode/cpuusage.pm
  src/network/f5/bigip/snmp/plugin.pm
  tests/network/f5/bigip/snmp/cpu.snmpwalk
  tests/network/f5/bigip/snmp/cpuusage.robot
Labels: skip-workflow-plugins
